.
This section is about building a simple mathematical model using the laws of a
straight line and the relation ship between revenue and costs. Mathematical
models use an equation or a system of equations to try and represent a real
life system or system. Real systems tend to be very complex and the more complex
the system typically the more complex the mathematics. It is also very
difficult to model any system in its entirety so the model tends to focus on
one aspect of a system and is valid only in certain instances.
.LP
There are some basic steps that must be completed in constructing the model and
the items below form the major components of operational research:
.IP \(en 
Observation - This is about gaining an understanding of the real world
situation so that the pertinent questions can be asked. This observation maybe
done directly or it can be through academic and scientific publications. In
agriculture there are many scientists working on genetics to improve yields and
growth rates in crops and livestock. This information is then fed through to
the producer and may cause you to reassess your own operations.
.IP \(en
Problem definition - The problems we are trying to answer below are based
around, costs, profits, revenues and quantities of production. A typical
question might be: how much should I pay for a store lamb for a finishing
operation? Another question might be, given that I want to sell all my lambs
before the traditional slump in prices in July, what is the minimum acceptable
growth rate?
.IP \(en
Model construction - Ascertain that the problem can be model with mathematics
and then:
.RS
.IP \(en
Understand which variables are important and which have little or no impact on
the outcome. If you are interested in the metric "days on farm" the the
variable that most interests you will be the growth rate, which is driven by
the milk yield of the ewe, which depends on the dry matter content of the feed
which the ewes has access to.
.IP \(en
Describe the problem in terms of mathematical equations. Equations will be
shown later in the section.
.RE
.IP \(en
Solutions - The validity of the model has to be checked. This is often done
against past results however this can be somewhat dangerous. By using past
results you are implying that the future and the past look the same or that
changes to the variables will follow the same patterns and have the same impact
as they did in the past. The testing of the validity of the model must
incorporate some expectations as to the future as well as examining the past
history. It is worth considering that the model will only be valid if the
variables, such as costs, can be controlled and other variables, such as price,
move as expected.
.IP \(en
Implementation - If the model is thought to be valid then a plan can be
developed to take advantage of the findings subject to the constraints under
which the model was built remaining constant or performing as expected.
.LP
Management can be loosely defined has having four functions; planning,
organising, leading and controlling. The construction of the model would fall
into the planning function if we accept that planning can be characterised as a
process to determine goals and define the steps required for their
accomplishment. The implementation falls into the categories of organising,
leadership and control and we are going to focus on the problems of control.
If we agree that the model is at best a poor representation of the reality of
any given real life situation and as such only holds true provided the
variables have some level of stability. This logically places a huge emphasis
on the control function of management. It is unlikely that any of the
variables are inherently stable however if they are inherently unstable it
makes the control of the process strenuous and it is subsequently unlikely that
the implementation of model will deliver the outcome that you want. This
uncertainty's aligns with the concept of risk as discussed in Chapter XX on the
cost of equity.
.LP
It is a given that management must be suitably organised so that the plan can
be appropriately executed but it must also be possible to exert control over
the variables to a level sufficient to deliver the required outcome. Is
therefore imperative that the planning process focuses on suitable means of
both controlling the variables or mitigating the impacting of large deviations
from the expected values.
.LP
Control and risk management are inextricably linked and there are many different
types of risk and we are only interest in the narrow sense that they apply in a
financial manner to the examples that follow. So, typically in this very narrow
sense it is allowing for such things as movements in the sale price, or
allowing for variations in the dry matter (DM) of a crop, or calculating the
repair cost associated with running a vehicle. It is assumed that other risks
associated with doing the business have been identified and steps identified to
mitigate them or eliminate them.
.LP
If changes are made to any of the systems then it is important to establish the
impact on the variables. For instance, you may decide not to have a quad bike
on the farm because it is difficult to control how fast people drive it and the
risk of serious and possible life altering injuries are too high to permit
its use. The risks associated with the quad bike have been identified as both
high and difficult to mitigate so the policy has been to eliminate them by
disposing of the quad bikes. The implication of this may be an increase in the
cost base if the quad is replaced with a gator or higher usage of a 4WD drive
truck. It is important to be conscious of the impact of changes on a system and
understand how this causes risks to change. One of the biggest problems to any
business is the variability of demand which at the extremes causes the
business to have very high levels of asset utilisation followed by periods of
very low asset utilisation these spikes cause planning problems for labour
requirements, parts supply etc. If long term contracts can be entered into the
demand can be stabilised but often this has the consequence of concentrating the
demand with a small number of customers. This concentration may be deemed the
lesser of the two risks but it should not be accepted with complacency.
.LP
Small business have a far less resources than large businesses and often the
owner must have a wide range of skills covering the technical aspects of the
business, the finance, marketing ecetera. For success a plan must be well
organised and easily controlled which leads to the logical conclusion that
small businesses in general should have simple business models. Lastly control
is expensive in terms of time taken in the planning stage but also through the
constant monitoring. Technology is constantly evolving to improve the ability
to monitor and control processes but the methods of control must be well
understood be they a simple time sheet or an electronic bolus for use in
livestock.
.
.XXXX \\n(cn 1 "Relating costs to revenue and profits"
.LP
Before we start we will define the variables that are used in examining the
relationship between the revenue and the costs:
.sp 0.5
.mk
.ll 2.9i
.nf
.ta 0.3i
TR	represents the total revenue
TC	represents the total costs
FC	represents the fixed costs
.fi
.br
.rt
.in 3.3i
.ll 6.0i
.nf
.ta 0.3i
VC	represents the variable costs
P	represents the selling price
Q	represents the quantity of units
.fi
.br
.sp
.LP
The first relationship we are going to look at is the revenue, which is
usually expressed as:
.EQ I
"Total revenue" lm "Price times quantity"
.EN
.sp -0.6v
.EQ I
TR lineup =~~ PQ
.EN
The above is fairly intuitive. In the simplest model the quantity demanded in a
function of the price. This assumes that the other variables that affect the
demand remain constant. The demand is affected by many factors such as: the
quantity of goods demanded, the income of the consumer, the price of substitute
goods, the price of complementary goods, the tastes of the consumer, the level
of advertising. We will talk more about price and demand as we work through the
examples later in the section. The basic premise is that as the price of a good
or service rises the quantity demanded will fall provided all other variables
remain constant.
.LP
We also have the supply side to contend with which is also a function of price.
Again the basic premise is that as the price of a good increases the quantity
supplied will also increase all other variables remaining constant. The
variables generally associated with supply are: the quantity of a good
supplied, the cost of production, the price of other goods, the number of
producers in the market, the available technology, other factors such as tax
and subsidy.
.LP
In breakeven analysis the relationship we are predominantly interested in is:
.EQ I
"Total costs" lm "Fixed costs" + "Variable costs" times "Quantity"
.EN
.sp -0.6v
.EQ I
TC lineup =~~
FC + VC(Q)
.EN
It should be apparent from the relationship above that as the production Q
increases the total costs increase. In the short run some of the costs are
fixed these include land, equipment, rent, salaried labour amongst others. Over
the long run all costs are variable but these costs take far longer to vary so
they can be thought of as fixed. The variable costs, on the other hand, vary
directly with the level of output and include the costs of raw materials,
components, energy, hourly paid labour amongst others. Although most costs for
simple projects can be classified readily in this way, it is not always a
straightforward task but unfortunately for the purposes of this analysis it can
not be avoided.
.LP
The average cost function can be found by dividing the total cost by the
output:
.EQ I
AC lm TC over Q
.EN
.sp -0.5v
.EQ I
lineup =~~
{ FC + VC(Q) }
over Q
.EN
.sp -0.5v
.EQ I
lineup =~~
FC over Q + VC over Q
.EN
.sp -0.5v
.EQ I
lineup =~~
FC over Q + VC
.EN
I have not included any graphs in this section which is somewhat of a failing
but at the beginning it was said that this section used the laws of a straight
line and you would subsequently expect the graphs to have straing lines. This
is not always the case, the supply and demand functions are not always linear
and the average cost function is often L shaped.
.LP
The last relationship we are going to examine is that of breakeven when the
profit is zero or more exactly the total revenue equals the total costs when
resolved for the quantity Q.
.EQ  I
~~~~~~~~~
TR lm TC
.EN
.sp -0.6v
.EQ I
P(Q) lineup =~~ FC~+~ VC(Q)
.EN
.sp -0.6v
.EQ I
P(Q) ~-~ VC(Q) lineup =~~ FC
.EN
.sp -0.6v
.EQ I
Q(P - VC) lineup =~~ FC
.EN
.sp -0.6v
.EQ I
Q lineup =~~ FC over left ( P - VC right )
.EN
The quantity #P - VC# is of interest in its own right, and is called the unit
contribution, it is the marginal profit per unit, or alternatively the portion
of each sale that contributes to the fixed costs. Thus the breakeven point can
be more simply stated as:
.EQ I
"Total contribution" lm "Total fixed costs"
.EN
.sp -0.6v
.EQ I
Q(P - VC) lineup =~~ FC
.EN
Breakeven is a widely used business tool but it is not without its limitations.
Traditionally breakeven analysis uses zero earnings as the breakeven point,
this ignores the cost of capital and investment requirements beyond the initial
investment. Therefore, break-even can \fBnot\fP be used to allocate capital.
In Appendix E we examine SVA as devised by Alfred Rappaport which is a form of
breakeven which includes the time value of money and can be used to allocated
capital within a business.
.LP
I am presuming that the cost of capital has been included in the fixed costs
using the information for the preceding Chapters. Therefore even if the
business operates close to the breakeven it will earn a sufficient reward to
compensate the investors for placing their capital in the business and should
theoretically return a NPV equal to zero.
.LP
There are also other limitation of breakeven:
.IP \(en
Break-even analysis only focuses on the costs and it tells you nothing about
what sales are actually likely to be for the product or service. 
.IP \(en
Break-even analysis assumes that fixed costs are constant. Although this is
generally true an increase in the scale of production is likely to cause fixed
costs to rise.
.IP \(en
Break-even analysis assumes that the variable costs are constant per unit of
output in the range of the likely quantities to be sold. In essence the
variable costs increase in a linear fashion.
.IP \(en
Break-even analysis assumes that the quantity of goods produced is equal to the
quantity of goods sold. This assumption means there should be no change in the
quantity of goods held in inventory at the beginning of the period and the
quantity of goods held in inventory at the end of the period.
.IP \(en
Break-even analysis assumes in companies with more than one product that the
sales mix remains constant. 
.LP
Now that we have outlined the general concept of breakeven we can examine some
examples or increasing complexity.
.
.XXXX 0 2 "Breakeven - forage harvest"
.LP
Wilbur is weighing up the possibility of investing in new forage harvester
and has established the following costs:
.TS
tab (#) center;
l l.
Initial purchase cost#\[Po]350,000
Annual revenues#\[Po]80 per hectare
Variable costs#\[Po]40 per hectare
Fixed operating costs per year#\[Po]20,000 increasing 1,000 per year
Annual insurance#\[Po]9,000 payable at the beginning of the year
Salvage value#\[Po]50,000
Useful life#10 years
.TE
Wilbur's cost of capital is 10%. How many hectares must the forager harvest to
justify the purchase?
.sp
.UL Method
.sp 0.5
This is a breakeven analysis with a number of considerations. The costs needs
to be converted to annual costs and then the number of hectares required per
year can be resolved.
.RS
.IP "Step 1:" 10
Set the left side of the equation equal to: "annual revenues" - "variable
costs" multiplied by the unknown variable, the number of hectares, represented
by #h#. The revenues less the variable costs will give the contribution
available per hectare to recover the fixed costs. The breakeven analysis is
covered in more detail in Chapter XX.
.IP "Step 2:" 10
The initial investment needs to be converted to an EAC using the Capital
Recovery factor.
.IP "Step 3:" 10
The 20,000 of fixed costs is already stated in terms of an annuity. However,
the increase of 1,000 can be converted to an annuity using the Arithmetic
Gradient Present Worth factor.\(dg
.IP "Step 4:" 10
Insurance is, usually, payable upfront as stated in this example. Therefore,
the insurance is a type of annuity due as covered in Chapter 5. We learnt in
Chapter 5 that a annuity due can be converted to an ordinary annuity by the
inclusion of an extra compounding period. Subsequently, the insurance cost must
be multiplied by the Single Payment Compound Amount factor.
.IP "Step 4:" 10
The salvage value must be converted to a present value using the Single Payment
Present Worth factor and an annuity using the Capital Recovery Factor.
.FS
\(dg In Chapter 11 we learnt that the arithmetic gradient factors are usually
used inconjucntion with an annuity equation. When working with annual costs the
the need to only calculate the annuity of the arithmetic gradient simplifies
the process.
.FE
.
.RE
.LP
.sp
.UL Calculation
.sp 0.5
.RS
.EQ I
(80-40)h lm -350,000(A/P, 10%, 10) - 20,000 - 1,000(A/G, 10%, 10)
- 9,000(F/P, 10%, 1)
.EN
.sp -0.6v
.EQ
lineup {hphantom{=~~}} 
-50,000(P/F, 12%, 10)(A/P, 12%, 10)
.EN
.sp -0.6v
.EQ I
lineup =~~
left [ -350,000 - 50,000(P/F, 12%, 10) right ] (A/P, 10%, 10) - 20,000 - 1,000(A/G, 10%, 10)
.EN
.sp -0.6v
.EQ I
lineup {hphantom{=~~}} 
- 9,000(F/P, 10%, 1)
.EN
.sp -0.6v
.EQ I
lineup =~~
left [ -350,000 - 50,000(0.3855) right ] (0.1627) - 20,000 - 1,000(3.7255)
- 9,000(1.10)
.EN
.sp -0.6v
.EQ I
lineup =~~
-60,081 - 20,000 -3,726 - 9,900
.EN
.sp -0.6v
.EQ I
lineup =~~
-93,707
.EN
We now how the revenue on the left side of the equation and the costs on the
right side of the equation. We have stuck with the convention of using positive
signs for the cash inflows and negative signs for the cash outflows. A
consequence of this will be that the answer is negative.
.EQ I
h lineup =~~ -93,707 over { 80 - 40 } 
.EN
.sp -0.5v
.EQ I
lineup =~~
-2,343
.EN
The absolute value is the answer: 2,343 hectares are required to break even.
.RE
.
.LP
Key points:
.IP \(en
The breakeven calculation includes the cost of capital and should result in the
business operating very close to its cost of capital and therefore the
investment would have a net present value of zero.
.IP \(en
The example does not include the working capital requirements of the forage
harvester such as spare parts inventories, and the increase in the receivable.
.IP \(en
The example has a long time frame over which the relationship between the
revenues and variable costs must remain the same and the costs must also not
rise any faster than anticipated.
.IP \(en
Wilbur would be advised to try and enter into some long term agreements to
secure the revenue and control the costs.
.
.XXXX 0 2 "Breakeven - haulage"
.LP
TO BE ADDED
.
.
.XXXX 0 2 "Breakeven - lamb finishing"
.LP
These formulas have been derived by examining the papers on the Agricultural
and Horticultural Development Board (AHDB) website which reference lamb
finishing.
.SH 
Symbols
.LP
.IP "#bw%#" 10
The percentage of body weight used to calculate the dry matter (DM)
required each day.
.IP "#c%#" 10
The marketing expense as a percentage of the sale price.
.IP "#cd#" 10
Carcass disposal.
.IP "#C sub U#" 10
Contribution per lamb.
.IP "#d#" 10
Days may refer to the days in a series, the days over which finance is
calculated or the days on farm. The days should be clear from the context.
.IP "#d sub f#" 10
The finish date of a time period.
.IP "#d sub s#" 10
The start date of a time period.
.IP "#DM sub d#" 10
The dry matter (DM) requirement for an individual lamb on a stated day
given a start weight, a growth rate and the percentage of body weight 
.IP "#DM sub ha#" 10
Dry matter per hectare.
.IP "#DM sub { \[sum] d }#" 10
The total dry matter consumed by an individual lamb over a stated number
of days given a start weight, finished weight and the percentage of body weight.
.IP "#DM sub { \[sum] r }#" 10
The total dry matter consumed by an individual lamb for a stated growth
rate given a start weight, finished weight and the percentage of body weight.
.IP "#DM sub { s\[->]f } #"
The dry matter required over a stated period. The subscript #s# represents the
day the period starts and the subscript #f# represents the day the period ends.
The start weight, finished weight and a growth rate must be given.
.IP "#DM sub t#" 10
Dry matter per tonne.
.IP "#FC#" 10
Fixed costs. These are understood to be labour #(l)#, power and machinery\(dd
#(mc)#, hire charges #(h)#, finance #(fn)# and all property and land rents
#(pr)#. The costs can have a subscript #b# or #s# to indicate whether they are
based on the number of lambs bought or sold.
.FS
\(dd There is no depreciation. It is expected that the machinery costs are
calculated using a capital recovery factor and include the time value of money.
.FE
.IP "#FC sub B#" 10
The fixed costs per lamb based on the number of lambs bought.
.IP "#FC sub S#" 10
The fixed costs per lamb based on the number of lambs sold.
.IP "#ha sub n#" 10
The hectares required per quantity of lambs.
.IP "#kg sub d #" 10
The kilograms of feed required per lamb on a stated day.
.IP "#kg sub { s\[->]f }#" 10
The kilograms required over a stated period of days.
.IP "#k sub f#" 10
The weight of the finished lamb in kilograms. This is equal to # k sub s + (d -
1)r #.
.IP "#k sub s#" 10
The weight of the store lamb in kilograms when it is purchased. 
.IP "#M#" 10
The margin you would like to make as an absolute value.
.IP "#M%#" 10
The margin you would like to make as a percentage.
.IP "#m%#" 10
The expected mortality rate as a percentage of the lambs purchased. The
mortality rate affects both the revenue and the costs. The revenue is reduced
through lost sales. The costs per lamb are increased by having to firstly
apportion the cost over a reduced number of lambs and secondly by the
additional cost of disposing of fallen stock.
.IP "#MC#" 10
The charge for the mortality. It is equal to the mortality rate #(m%)# times
the carcass disposal cost #(cd)#.
.IP "#m sub d sup 2 #" 10
The area of crop required per lamb on a stated day.
.IP "#m sub { s\[->]f } sup 2#" 10
The area required over a stated period of days.
.IP "#OW#" 10
The costs of the weight that is originated on the farm to get the lamb from the
store weight to the finished weight. These costs are finance, fuel, repair,
maintenance, forage and hay and are calculated on a daily basis.
.IP "#d (OW sub B )#" 10
The daily costs of originating weight on farm based on the number of lambs bought.
.IP "#d (OW sub S )#" 10
The daily costs of originating weight on farm based on the number of lambs sold.
.IP "#P sub 1#" 10
The price per kg paid for the store lamb.
.IP "#P sub 2#" 10
The sale price per kg before any deductions are made for sales commissions.
.IP "#P sub 3#" 10
The sale price achieved after sales commission is deducted.
.IP "#PW#" 10
This represents the purchase of the store lamb and its direct costs. The
purchased weight #(PW)# is a function of the price per kilograms times
kilograms #k sub s ( P sub 1 )# + vet #(v)# + transport #(t)#. These costs are
typically fixed variable costs.  They are fixed in so much as they are
relatively constant per lamb and a variable cost as they increase with the
number of lambs to be finished.
.IP "#PW sub B#" 10
Purchased weight based on the lambs bought with no mortality charge.
.IP "#PW sub S#" 10
The purchase weight including a charge for mortality. It is equal to #PW sub
B + MC#.
.IP "#Q sub B#" 10
The number of store lambs which have been purchased. Unfortunately the
number of lambs bought and the number of lambs which are sold and not the same
due to the mortality rate.
.IP "#Q sub S#" 10
The number of lambs that will actually be sold after mortality. It is
equal to #Q sub B (1 - m%)#.
.IP "#r#" 10
The rate of gain in kilograms per head per day.
.IP "#R sub U#" 10
Revenue per lamb.
.IP "#t sub n#" 10
The tonnes of hay required per quantity of lambs. 
.IP "#TC#" 10
Total costs
.IP "#TC sub TB#" 10
The total costs per lamb based on the total costs divided by the number of
lambs bought. It is equal to # { FC + ( VC sub TS ) Q sub S } over Q sub B #
.IP "#TC sub TS#" 10
The total costs per lamb based on the total costs divided by the number of
lambs sold. It is equal to # { FC + [ VC sub TS ] Q sub S } over Q sub S #
.IP "#TR#" 10
Total revenue.
.IP "#TVC sub B#" 10
The total variable costs based on the number of lambs bought. It is equal to 
# Q sub B left [ PW sub B + d ( OW sub B ) right ] #
.IP "#TVC sub S#" 10
The total variable costs based on the number of lambs sold. It is equal to # Q
sub B (PW sub S ) + d ( OW sub S ) Q sub S #
.IP "#u sub f#" 10
The utilisation rate for the forage crop, stubble turnips
.IP "#u sub h#" 10
The utilisation rate for the hay
.IP "#VC#" 10
Variable costs are the purchased weight #(PW)# and the weight originated on
farm #(OW)#. Variable costs are by definition unit costs as they vary with the
level of production. The costs are finance #(fsl)#, fuel #(fl)#, repair #(rp)#,
maintenance #(mn)#, forage #(fo)# and hay #(hy)#. The costs can have a
subscript #b# or #s# to indicate whether they are based on the number of lambs
bought or sold.
.IP "#VC sub B#" 10
The variable costs per lamb based on the number of lambs bought. It is equal to
# PW sub B + d( OW sub B ) #
.IP "#VC sub S#" 10
The variable costs per lamb based on the number of lambs sold. It is equal to #
PW sub S + d ( OW sub S ) #
.IP "#VC sub TB#" 10
The variable costs per lamb based on the total variable costs divided by the
number of lambs bought. It is equal to # TVC sub B over Q sub B #
.IP "#VC sub TS#" 10
The variable costs per lamb based on the total variable costs divided by the
number of lambs sold. It is equal to # TVC sub S over Q sub S #
.IP "#y sub f#" 10
The fresh yield for a forage crop.
.IP "#y sub dm#" 10
The percentage of a crop that is dry matter.
.IP "#\[*p] sub u#" 10
Profit per lamb
.IP "#\[*p]#" 10
Total profit
.
.SH
Example scenario
.LP
We can now create a scenario, to use through out the document, based around
lamb finishing on stubble turnips, again the numbers are not meant to be
accurate nor all the costs that you might incur included. 
.IP \(bu
The target is to finish 3,000 lambs
.IP \(bu
The target growth rate is 0.15 kg per day
.IP \(bu
The target sale weight of the lamb is 42 kg (alive)
.IP \(bu
The store lamb is assumed to weigh 30 kg #(k sub s )# and cost \[Po]45 given a
cost per kg #(P sub 1 )# of \[Po]1.50.
.IP \(bu
The target days on farm are 81. With a finished weight of 42 kg and a growth
rate of 0.15 kg the purchased store lamb should not weigh less than 30 kg.
.EQ I
"Target store weight" ~~ ( k sub s ) lm
"Sale weight" - ( days - 1 ) times "rate of gain per day"
.EN 
.sp -0.6v
.EQ I
k sub s lineup =~~
k sub f - ( d - 1 ) r
.EN
.sp -0.6v
.EQ I
lineup =~~
42 - ( 81 - 1 ) 0.15
.EN
.sp -0.6v
.EQ I
lineup =~~
30 ~kg
.EN
.sp -0.5
.IP \(bu
For the purposes of this scenario, assume that the turnips are planted and are
then available for use 90 days later. The turnips are to be grazed  for
approximately 120 days. The target days on farm are 81, which means there are
39 days to acquire the store lambs and get them on farm.
.IP \(bu
Fresh yield on the stubble turnips is 50,000 kg/ha
.IP \(bu
Dry matter content is 13.5% of the fresh yield for the stubble turnips.
.IP \(bu
Establishment costs for the stubble turnips are \[Po]300/ha
.IP \(bu
Utilisation for the stubble turnips is estimated at 80%
.IP \(bu
Stubble turnips are high in energy and low in protein and fibre consequently
the lambs should have access to supplementary protein and hay or straw. The hay
or straw should make up 30% of the diet. As the lambs get larger and closer to
their mature weight their protein requirement falls.
.IP \(bu
Dry matter for the hay is 85%
.IP \(bu
Hay is purchased at \[Po]50 per tonne
.IP \(bu
Utilisation for the hay is estimated at 70%
.IP \(bu
The labour cost is one third of a full time labour unit at \[Po]40,000 which equates
to \[Po]12,000
.IP \(bu
The property and rents are \[Po]6,000 for the year.
.IP \(bu
The equivalent annual cost (EAC) for the machinery is \[Po]11,000. This
includes the 4WD, Pratley yard, electronic weigh crate, ATV, fencing equipment
and trailers.
.IP \(bu
The EAC for the maintenance is \[Po]1,000
.IP \(bu
The EAC for the repairs is \[Po]1,700
.IP \(bu
The lambs need checking every day, which is a 25 mile round trip and there is a
contingency of 10 miles per day accumulated through use of the 4WD for fencing,
carcass disposal and other ancillary tasks.  The fuel economy of the vehicle is
expected to be 20 mpg as the vehicle will predominantly be towing some form of
trailer. The costs of fuel is \[Po]1.00 per litre which means the total fuel
cost is:
.EQ I
"Fuel cost" lm
{ ( Mileage + Contingency ) times Days times "Liter/gallon" times "\[Po]/liter" } 
over
mpg
.EN
.EQ I
lineup =~~
{ (25 + 10)(120)(4.54)(1.0)} over 20
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]953
.EN
.sp -0.5
.IP \(bu
Marketing costs are 3% of the sale price. 
.IP \(bu
Transport is \[Po]2 per lamb
.IP \(bu
Vet is \[Po]3 per lamb
.IP \(bu
Carcass disposal is \[Po]15 per deceased lamb
.IP \(bu
The presumption is that the lamb purchase and the crop are financed with a
revolving credit facility using simple interest at 10% and 365 days in a year.
.
.XXXX 0 3 "Dry matter requirements"
.LP
This section examines some formulas to calculate the dry matter required for an
individual lamb. Growing lambs generally require 4%\(dd of their body weight as
dry matter per day, if it is wet then this value will need to be increased due
to the loss of utilisation.
.FS
\(dd It is not uncommon to see 5% used as the dry matter requirement per day.
.FE
The target finishing weight is a function of the purchase weight, available
days on farm and the growth rate.
.EQ I
"Target finished weight" ~~ k sub f lm "Store weight"
+ ( days - 1) times "rate of gain per day"
=~~ k sub s + (d - 1 )\(dg r
.EN
.FS
\(dg The #(d - 1)# is needed so that the dry matter requirement on day one is
calculated on the store weight and does not include any growth.
.FE
The formula above can then be rearranged to resolve for the other variables if
required:
.
.EQ I
"Target growth rate" ~~r =~~
{ "Finished weight" - "store weight" } over { days - 1 }
=~~ { k sub f - k sub s } over { ( d - 1 ) }
.EN
.
.EQ I
"Target days on farm" ~~d =~~ 
{ "Finished weight" - "store weight" } over "rate of gain per day" + 1
=~~
left [ { k sub f - k sub s } over r right ] + 1
.EN
.
.EQ I
"Target store weight" ~~ k sub s =~~
"Sale weight" - ( days - 1 ) times "rate of gain per day"
=~~ k sub f - ( d - 1 ) r
.EN
The formulas above can be combined with the formula for an arithmetic series to
calculate the dry matter requirements over given time periods. The formulas have
been derived in Appendix N.
.
.XXXX 0 4 "Dry matter per lamb"
.LP
The dry matter requirement of the lamb rises as at it gains body weight. The
dry matter requirement on any given day can be expressed as:
.EQ I
DM sub d  lm ( "Store weight" + ( day times "growth rate") )
times " % body weight"
.EN
.sp -0.6v
.EQ I
lineup =~~ ( k sub s + (d -1) r ) times %bw
.EN
A lamb purchased with a 30 kg body weight and an expected growth rate of 0.15
kg per day has the dry matter requirement below on day 1:
.EQ I
DM sub 1 lm ( k sub s + (d -1)r ) times %bw
.EN
.sp -0.6v
.EQ I
lineup =~~
(30 + (1 - 1)(0.15)) times 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
30 times 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
1.2 ~kg ^per ^lamb
.EN
.
The dry matter requirement of a lamb, at day 60, when purchased at a weight of
30 kg with a growth rate of 0.15 kg per day will be:
.EQ I
DM sub 60 lm ( k sub s + (d - 1)r ) times %bw
.EN
.sp -0.6v
.EQ I
lineup =~~ ( 30 + (60 -1)(0.15) ) times 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
(30 + 8.85) times 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
1.55 ~kg ^per ^lamb
.EN
.
.XXXX 0 4 "Dry matter over number of days given a start and finish weight"
.LP
The equation below has been derived in Appendix N and allows us to calculate
the amount of dry matter a lamb will consume over a given number of days to
reach a given weight.
.EQ I
DM sub { \[sum] d } lm
d over 2 left [ k sub s + k sub f  right ] %bw
.EN
.KS
An example to make things clearer, I hope. A lamb is purchased at 30 kg and
will be sold at a finished weight of 42 kg. If the lamb reaches this weight in
81 days how much dry matter will it have consumed?
.EQ I
DM sub { \[sum] 81 } lm
d over 2 left [ k sub s + k sub f  right ] %bw
.EN
.sp -0.6v
.EQ I
lineup =~~
81 over 2 left [ 30 + 42 right ] 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
40.5 left [ 72 right ] 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
116.64 ~kg ^DM ^per ^lamb
.EN
.KE
In the scenario above the lamb is taken from 30 kg to 42 kg live weight in 81
days. It is important to understand that if the lamb takes longer to reach the
desired finishing weight it will consume more feed and subsequently have a
higher feed cost. We will increase the days to 110 and see the impact on the
kilograms of dry matter.
.EQ I
DM sub { \[sum] 110 } lm
d over 2 left [ k sub s + k sub f  right ] %bw
.EN
.sp -0.6v
.EQ I
lineup =~~
110 over 2 left [ 30 + 42 right ] 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
55 left [ 72 right ] 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
158.40 ~kg ^DM ^per ^lamb
.EN
The number of days required to reach the finishing weight was increased from 81
to 110, this is an increase in the time of 36%. Extending the number of days
has resulted in the amount of dry matter required increasing from 116.64 kg to
158.40 kg, this is also an increase of 36%. The relationship between the
percentage increase in the number of days and the percentage increase in the
required amount of dry matter should hold true, but I would advise completing
the calculation for the dry matter.
.LP
The number of days taken to reach a desired weight implies a growth rate. The
growth rate can be checked by using the following formula:
.EQ I
"Target growth rate" ~~r =~~
{ "Finished weight" - "store weight" } over { days - 1 }
=~~ { k sub f - k sub s } over { ( d - 1 ) }
.EN
The growth rate for 81 days:
.EQ I
r =~~ { k sub f - k sub s } over { ( d - 1 ) }
=~~ { 42 - 30 } over { ( 81 - 1 ) }
=~~ 0.15 ~kg ^per ^day
.EN
The growth rate for 110 days:
.EQ I
r =~~ { k sub f - k sub s } over { ( d - 1 ) }
=~~ { 42 - 30 } over { ( 110 - 1 ) }
=~~ 0.11 ~kg ^per ^day
.EN
So, a target number of days implies a given growth rate and a given growth rate
implies that the lamb will reach finishing weight in a given number of days.
.
.XXXX 0 4 "Dry matter given a growth rate and a start and finish weight"
.LP
The equation below has been derived in Appendix N and allows us to calculate
the amount of dry matter a lamb will consume to reach a finishing weight if the
start weight and growth rate are known.
.EQ I
DM sub { \[sum] r }  lm
{ { k sub f - k sub s + r } over 2r }
left [ k sub s + k sub f right ] %bw
.EN
.KS
A lamb is purchased at 30 kg and will be sold at a finished weight of 42 kg. If
the growth rate is 0.15 kg per day how much dry matter will it have consumed to
reach the finishing weight?
.EQ I
DM sub { \[sum] 0.15 } lm
{ { k sub f - k sub s + r } over 2r }
left [ k sub s + k sub f right ] %bw
.EN
.sp -0.6v
.EQ I
lineup =~~
{ { 42 - 30 + 0.15 } over 2(0.15) }
left [ 30 + 42 right ] 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
{ { 12.15 } over 0.3 }
left [ 72 right ] 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
40.5 left [ 72 right ] 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
116.64 ~kg ^DM ^per ^lamb
.EN
.KE
This is the same value as we calculated in the previous section as the weights
are the same and we used the growth rate implied by 81 days in the previous
section. You can either think in terms of days or growth rates as they are
different sides of the same coin. As we have previously stated a growth rate
implies a given number of days required to reach the finishing weight and the
number of days implies the growth rate required to reach the finishing weight.
We will change the growth rate to see the impact on the kilograms of dry
matter. We will use a low growth rate of 0.09 kg per day.
.EQ I
DM sub { \[sum] 0.09 } lm
{ { k sub f - k sub s + r } over 2r }
left [ k sub s + k sub f right ] %bw
.EN
.sp -0.6v
.EQ I
lineup =~~
{ { 42 - 30 + 0.09 } over 2(0.09) }
left [ 30 + 42 right ] 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
{ { 11.91 } over 0.18 }
left [ 72 right ] 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
66.17 left [ 72 right ] 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
190.56 ~kg ^DM ^per ^lamb
.EN
The amount of dry matter consumed has risen by 63% even though the growth rate
has only been reduced by 40%. We have previously noted the relationship between
the percentage increase in the number of days and the percentage increase in
the required dry matter. The relation can be found in this example if the
growth rate is converted into the implied number of days. We know that the
growth rate of 0.15 kg per day with the weights in our example results in 81
days on farm. The growth rate of 0.09 kg per day result in 190.56 kg of dry
matter and this implies 133 days days on farm:
.EQ I
"Target days on farm" ~~d =~~ 
{ "Finished weight" - "store weight" } over "rate of gain per day" + 1
=~~
left [ { k sub f - k sub s } over r right ] + 1
=~~
{ 42 - 30 } over 0.09 + 1
=~~
133
.EN
The percentage increase in days from 81 to 133 is 64% which closely matches the
increase in the dry matter requirement.
.
.XXXX 0 4 "Dry matter over a time period"
.LP
The equation below has been derived in Appendix N and allows us to calculate
the amount of dry matter, in kilograms, required over a time period in days.
.EQ I
DM sub { s\[->]f } lm
{  d sub f - d sub s  + 1  } over 2
left [ 2 k sub s 
+
r ( d sub f + d sub s - 2 ) right ] %bw 
.EN
A lamb is purchased at 30 kg and will spend 81 days on farm. If the growth rate
is 0.15 kg per day how much dry matter will it have consumed in the first 30
days?
.EQ I
DM sub { 1\[->]30 } lm
{  d sub f - d sub s  + 1  } over 2
left [ 2 k sub s 
+
r ( d sub f + d sub s - 2 ) right ] %bw 
.EN
.sp -0.6v
.EQ I
lineup =~~
{  30 - 1  + 1  } over 2
left [ 2 (30) 
+
0.15 ( 30 + 1 - 2 ) right ] 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
15 left [ 60 + 4.35 right ] 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
15 left [ 64.35 ] 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
38.61 ~kg ^DM ^per ^lamb
.EN
38.61 kg is the sum of the daily dry matter requirements for day 1 through to
and including day 30. If you want the dry matter requirements for the second
month you would need to use days 31 to 60. If you want to then calculate the
remaining dry matter requirement based on our example of 81 days you would need
to use days 61 through to 81.
.LP
We have been working with our example of fattening a lamb from 30 kg to 42 kg
over 81 days which implies a growth rate of 0.15 kg per day. We will now
calculate the feed requirements over the remaining time period which is day 31
to 81.
.EQ I
DM sub { 31\[->]81 } lm
{  d sub f - d sub s  + 1  } over 2
left [ 2 k sub s 
+
r ( d sub f + d sub s - 2 ) right ] %bw 
.EN
.sp -0.6v
.EQ I
lineup =~~
{  81 - 31  + 1  } over 2
left [ 2 (30) 
+
0.15 ( 81 + 31 - 2 ) right ] 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
25.5 left [ 60 + 16.5 right ] 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
25.5 left [ 76.50 ] 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
78.03 ~kg ^DM ^per ^lamb
.EN
We previously calculated the kilograms of dry matter required to finish a lamb
at 42 kg, starting at 30 kg, given a growth rate of 0.15 kg per day as 116.64
kg DM. 
.EQ I
DM sub { \[sum] 81 } lm DM sub { 1\[->]30 } + DM sub { 31\[->]81 }
.EN
.sp -0.6v
.EQ I
lineup =~~
38.61 + 78.03
.EN
.sp -0.6v
.EQ I
lineup =~~
116.64 ~kg ^DM ^per ^lamb
.EN
The great advantage of this formula is that you need only know the weight of
the store lamb when it was purchased and not its weight at the start of the
time period to calculate the feed consumed.
.
.XXXX 0 3 "Feed requirements"
.LP
If the forage crop represents 70% percent of the diet the remaining 30% must
come from the hay. It is presumed the hay is placed on the headland around the
fields when the forage crop is planted so there is no requirement to drive on
the fields later in the year. In our scenario feeding the hay on the headland
leads to a low utilisation rate of 70%. 
.
.XXXX 0 4 "Forage kg DM/ha"
.LP
We will use the figures from our example scenario. The stubble turnips have a
fresh yield of 50,000 kg/ha, 13.5% DM and 80% utilisation.
.EQ I
DM sub ha lm "Fresh yield" times "DM% of fresh yield" times "Utilisation"
.EN
.sp -0.6v
.EQ I
lineup =~~ y sub f times y sub dm times u sub t
.EN
.sp -0.6v
.EQ I
lineup =~~
50,000 times 0.135 times 0.8
.EN
.sp -0.6v
.EQ I
lineup =~~
5,400 ~"kg/ha"
.EN
.
.XXXX 0 4 "Hay kg DM/tonne"
.LP
The figures for the hay are 85% DM and 70% utilisation.
.EQ I
DM sub t lm 1,000 times "DM%" times "Utilisation"
.EN
.sp -0.6v
.EQ I
lineup =~~ 1,000 times y sub dm times u sub t
.EN
.sp -0.6v
.EQ I
lineup =~~
1,000 times 0.85 times 0.7
.EN
.sp -0.6v
.EQ I
lineup =~~
595 ~"kg/tonne"
.EN
.
.XXXX 0 4 "Forage hectares required"
.LP
The number of hectares required is:
.EQ I
ha sub n lm
Q sub B over { DM sub ha over { DM sub { \[sum] d } (%Diet) } }
=~~
{  Q sub B ( DM sub { \[sum] d } ) %Diet } over { DM sub ha }
.EN
The number of hectares required for 3,000 lambs based on our assumption of
approximately 117 kg of dry matter consumed over 81 days are:
.EQ I
ha sub 3,000 lm
{  Q sub B ( DM sub { \[sum] d } ) %Diet } over { DM sub ha }
.EN
.sp -0.6v
.EQ I
lineup =~~
3,000(117)0.7 over 5,400
.EN
.sp -0.6v
.EQ I
lineup =~~
241,500 over 5,400
.EN
.sp -0.6v
.EQ I
lineup =~~
46 ~"ha"
.EN
The amount of hectares per lamb is found by setting the target number of lambs
equal to 1:
.EQ I
ha sub 1 lm
{ 1 ( DM sub { \[sum] d } ) %Diet } over { DM sub ha }
.EN
.sp -0.6v
.EQ I
lineup =~~
1(117)0.7 over 5,400
.EN
.sp -0.6v
.EQ I
lineup =~~
81.9 over 5,400
.EN
.sp -0.6v
.EQ I
lineup =~~
0.015 ~ha ^per ^lamb
.EN
.
.XXXX 0 4 "Tonnes of hay required"
.LP
The calculation for the amount of hay is shown below:
.EQ I
"Hay required" =~~
{ ("Target number of lambs") ( DM sub { \[sum] d } ) (%Diet) }
over { ( "DM% hay" ) ( "Utilisation hay" ) (1,000) }
.EN
This can be expressed in symbols as:
.EQ I
t sub n =~~
{  Q sub B ( DM sub { \[sum] d } ) %Diet }
over {  y sub dm  ( u sub h ) 1,000 }
.EN
The requirements based on our example are:
.EQ I
t sub 3,000 lm
{  Q sub B ( DM sub { \[sum] d } ) %Diet }
over {  y sub dm  ( u sub h ) 1,000 }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ 3,000 ( 117 ) 0.3 }
over {  0.85  ( 0.7 ) 1,000 }
.EN
.sp -0.6v
.EQ I
lineup =~~
105,300
over
595
.EN
.sp -0.6v
.EQ I
lineup =~~
177 ~"tonnes"
.EN
The utilisation for the hay is very low at 70% which implies that 30% is going
to waste. In this instance that amounts to # 0.3 times 177# which equates to 53
tonnes. A troubling thought.
.LP
The individual requirement for hay can be calculated by setting the target
number of lambs to 1:
.EQ I
t sub 1 lm
{ 1 ( DM sub { \[sum] d } ) %Diet }
over {  y sub dm  ( u sub h ) 1,000 }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ 1( 117 ) 0.3 }
over {  0.85  ( 0.7 ) 1,000 }
.EN
.sp -0.6v
.EQ I
lineup =~~
35.1
over
595
.EN
.sp -0.6v
.EQ I
lineup =~~
0.059 ~tonnes ^ per ^ lamb
.EN
.
.KS
.XXXX 0 4 "Check feed requirements"
.LP
We previously calculated the individual dry matter requirements as 116.64 kg
and the total dry matter for 3,000 lambs would be approximately 349,920 kg. It
is prudent to check that the individual feed requirements total the same
approximate number:
.EQ I
"Total DM" lm "Stubble turnips" + Hay
.EN
.sp -0.6v
.EQ I
lineup =~~
ha sub 3,000 times DM sub ha
+ t sub 3,000 times 1,000 times y sub dm times u sub h
.EN
.sp -0.6v
.EQ I
lineup =~~
( 46 ) ( 5,400 ) + 177 (1,000) (0.85) (0.7)
.EN
.sp -0.6v
.EQ I
lineup =~~
248,400 + 105,315
.EN
.sp -0.6v
.EQ I
lineup =~~
353,715 ~kg
.EN
.KE
The numbers are not exact due to the rounding, but they are close enough to
feel confident that the individual feed calculations are correct.
.
.XXXX 0 4 "Forage area per day"
.LP
The area required per day in #m sup 2# is given by the equation below:
.EQ I
m sub d sup 2  lm
{ ("Store weight" +  (day - 1)  times "growth rate") times 10,000 times %Diet }
over 
{ "Fresh yield kg/ha" times "DM% of fresh yield" times "Utilisation" }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ DM sub d times 10,000 times %Diet } 
over
{ DM sub ha }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ ( k sub s + (d -1)r ) times %bw times 10,000 times %Diet} 
over
{ y sub f times y sub dm times u sub t }
.EN
What is the area requirement for a lamb on day 1 if it is purchased weighing
30 kg using the criteria from the example scenario?
.EQ I
m sub 1 sup 2 lm
{ ( k sub s + (d -1)r ) times %bw times 10,000 times %Diet} 
over
{ y sub f times y sub dm times u sub t }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ ( 30 + (1 -1)0.15 ) times 0.04 times 10,000 times 0.7} 
over
{ 50,000 times 0.135 times 0.8 }
.EN
.sp -0.6v
.EQ I
lineup =~~
8,400
over 
5,400
.EN
.sp -0.6v
.EQ I
lineup =~~
1.56 ~m sup 2 ^ per ^ lamb
.EN
What is the area requirement at day 70?
.EQ I
m sub 70 sup 2 lm
{ ( k sub s + (d -1)r ) times %bw times 10,000 times %Diet} 
over
{ y sub f times y sub dm times u sub t }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ ( 30 + (70 -1)0.15 ) times 0.04 times 10,000 times 0.7} 
over
{ 50,000 times 0.135 times 0.8 }
.EN
.sp -0.6v
.EQ I
lineup =~~
11,298
over 
5,400
.EN
.sp -0.6v
.EQ I
lineup =~~
2.09 ~m sup 2 ^ per ^ lamb
.EN
The total area required for a mob can be calculated by multiplying by the
quantity of lambs.
.
.XXXX 0 4 "Hay kg per day"
.LP
The hay required per day in kilograms is given by the equation below:
.EQ I
kg sub d lm
{ ("Store weight" + ( day - 1 ) times "growth rate") times %Diet }
over 
{ "DM% Hay" times "Utilisation hay" }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ DM sub 1 times %Diet } 
over
{ y sub dm times u sub h }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ ( k sub s + (d -1)r ) times %bw times %Diet} 
over
{ y sub dm times u sub h }
.EN
How may kilograms of hay are required for a lamb on day 1 if it is purchased
weighing 30 kg using the criteria from the example scenario?
.EQ I
kg sub 1 lm
{ ( k sub s + (d -1)r ) times %bw times %Diet} 
over
{ y sub dm times u sub h }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ ( 30 + (1 -1)0.15 ) times 0.04 times 0.3} 
over
{ 0.85 times 0.7 }
.EN
.sp -0.6v
.EQ I
lineup =~~
0.36
over 
0.60
.EN
.sp -0.6v
.EQ I
lineup =~~
0.61 ~kg ^ per ^ lamb
.EN
How many kilograms of hay are required on day 70?
.EQ I
kg sub 70 lm
{ ( k sub s + (d -1)r ) times %bw times %Diet} 
over
{ y sub dm times u sub h }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ ( 30 + (70 -1)0.15 ) times 0.04 times 0.3} 
over
{ 0.85 times 0.7 }
.EN
.sp -0.6v
.EQ I
lineup =~~
0.48
over 
0.60
.EN
.sp -0.6v
.EQ I
lineup =~~
0.80 ~kg ^ per ^ lamb
.EN
The total kilograms required for a mob can be calculated by multiplying by the
quantity of lambs.
.
.XXXX 0 4 "Area, per lamb, over a time period"
.LP
The area required for a time period can be calculated by first calculating the
dry matter over a time period using the same formula as before and then
converting this value into #m sup 2#.
.EQ I
m sub { s\[->]f } sup 2  lm
{ DM sub "s\[->]f" times 10,000 times %Diet } 
over
{ DM sub ha }
.EN
The formula for the dry matter is:
.EQ I
DM sub { s\[->]f } lm
{  d sub f - d sub s  + 1  } over 2
left [ 2 k sub s 
+
r ( d sub f + d sub s - 2 ) right ] %bw 
.EN
First we will calculate the dry matter over a number of days for instance days
7 to 14:
.EQ I
DM sub { 7\[->]14 } lm
{  d sub f - d sub s  + 1  } over 2
left [ 2 k sub s 
+
r ( d sub f + d sub s - 2 ) right ] %bw 
.EN
.sp -0.6v
.EQ I
lineup =~~
{  14 - 7  + 1  } over 2
left [ 2 (30) 
+
0.15 ( 14 + 7 - 2 ) right ] 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
4 left [ 60 + 2.85 right ] 0.04
.EN
.sp -0.6v
.EQ I
lineup =~~
10.06 ~kg ^DM ^ per ^ lamb
.EN
We can now convert the dry matter into an area:
.EQ I
m sub { 7\[->]14 } sup 2  lm
{ DM sub "7\[->]14" times 10,000 times %Diet } 
over
{ DM sub ha }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ 10.06 times 10,000 times 0.7 }
over
5,400
.EN
.sp -0.6v
.EQ I
lineup =~~
13.04 ^m sup 2 ^ per ^ lamb
.EN
.
.XXXX 0 4 "Hay in kg, per lamb, over a time period"
.LP
We will use the same technique as we used for the area. Firstly you must
calculate the dry matter in kilograms required over a time period and then it
can be converted to the kilograms of hay. I am not going to redo the
calculation so we will use the same time period as we used for the area, days 7
to 14.
.EQ I
kg sub { s\[->]f }  lm
{ DM sub { s\[->]f } times %Diet } 
over
{ y sub dm times u sub h }
.EN
.KS
The kilograms of hay required is:
.EQ I
kg sub { 7\[->]14 }  lm
{ DM sub { 7\[->]14 } times %Diet } 
over
{ y sub dm times u sub h }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ 10.06 times 0.3 }
over
0.6
.EN
.sp -0.6v
.EQ I
lineup =~~
5.03 ~kg
.EN
.KE
.
.XXXX 0 3 "Costs"
.LP
In this section we move from thinking in terms of dry matter and look at the
costs of the inputs in a number of ways.
.
.XXXX 0 4 "Fixed costs"
.LP
The fixed costs are understood to be labour, machinery, hire, fuel, finance and
property.
.EQ I
FC lm Labour + machinery + hire + fuel + finance + property 
.EN
The hire charge is to cover the short term requirement for a loader tractor or
telehandler to move the bales onto the headland. The fixed finance cost is the
cost of establishing the crop and purchasing the hay. For the purposes of this
exercise it is presumed that the hay is purchased at the same time the forage
crop is established and therefore they are both financed over the same time
period. The time period, for the purpose of the finance calculation is 210 days
which is the 90 days after establishment, until the crop can be grazed, and the
following 120 days over which the grazing occurs.
.EQ I
Finance lm { left [ ( "ha forage" times "\[Po]/ha" )
+
( "Tonnes hay" times "\[Po]/tonne" ) right ] times "Interest rate%" times Days }
over
365
.EN
.sp -0.6v
.EQ I
lineup =~~
{ left [ ( 45 times 300 ) + ( 172 times 50 ) right ] times 0.1 times 120 }
over
365
.EN
.sp -0.6v
.EQ I
lineup =~~
261,600 over 365
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]1,272
.EN
The fixed costs can now be totalled:
.EQ I
FC lm Labour + machinery + hire + finance + property 
.EN
.sp -0.6v
.EQ I
lineup =~~
l + mc + h + fn + pr
.EN
.sp -0.6v
.EQ I
lineup =~~
12,000 + 11,000 + 2,000 + 1,272 + 6,000
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]32,272
.EN
The amounts can also be displayed in a table:
.TS
tab (#) center;
l n n.
Labour#\[Po]12,000#37%
Machinery#\[Po]11,000#34%
Hire#\[Po]2,000#6%
Finance#\[Po]1,272#4%
Property & rents#\[Po]6,000#19%
#_
Fixed costs#\[Po]32,272
#_
.TE
.KS
It can be seen that the largest fixed costs in our example is the labour. The
labour, machinery and property account for 90% of the fixed costs.
The fixed costs per bought lamb are:
.EQ I
FC sub B lm FC over Q sub B
.EN
.sp -0.6v
.EQ I
lineup =~~
{ l + mc + h + fn + pr } over Q sub B 
.EN
.sp -0.6v
.EQ I
lineup =~~
{ 12,000 + 11,000 + 2,000 + 1,272 + 6,000 } over 3,000
.EN
.sp -0.6v
.EQ I
lineup =~~
4.00 + 3.67 + 0.67 + 0.42 + 2.00
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]10.76 ~per ^lamb
.EN
.KE
The problem is that the number of lambs sold will not be the same as the number
of lambs bought due to the mortality rate.  We did not include the mortality
rate when accounting for the forage because we do not know when the lambs are
going to die. They may die on the first day or the last day when they have
consumed their allocated amount of feed. 
.LP
When examining the costs we can not avoid the mortality rate, however, we can
account for it at different points in the calculations. We are going to account
for the mortality rate at the individual cost level and display it alongside
the unadjusted figure so that we can compare the two figures.
.LP
The number of lambs sold is equal to the number of lambs bought multiplied by
#1 - "mortality rate"#.
.EQ I
Q sub S =~~ Q sub b ( 1 - m%) =~~ 3,000( 1 - 0.03) = 2,910
.EN
The calculation for the fixed costs per lamb sold is then as as follows:
.EQ I
FC sub S lm FC over Q sub S
.EN
.sp -0.6v
.EQ I
lineup =~~
{ l + mc + h + fn + pr } over Q sub S
.EN
.sp -0.6v
.EQ I
lineup =~~
{ 12,000 + 11,000 + 2,000 + 1,272 + 6,000 } over { 3,000(1 - m%) }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ 12,000 + 11,000 + 2,000 + 1,272 + 6,000 } over 2,910
.EN
.sp -0.6v
.EQ I
lineup =~~
4.12 + 3.78 + 0.69 + 0.44 + 2.06
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]11.09 ~per ^lamb
.EN
These unit costs can also be displayed in a table:
.EQ I
delim @@
.EN
.TS
tab (#) center;
l c c
l c c
l n .
#_#_
#@FC sub B@#@FC sub S@
#_#_
Labour#\[Po]4.00#\[Po]4.12
Machinery#\[Po]3.67#\[Po]3.78
Hire#\[Po]0.67#\[Po]0.69
Finance#\[Po]0.42#\[Po]0.44
Property & rents#\[Po]2.00#\[Po]2.06
#_#_
Unit fixed costs#\[Po]10.76#\[Po]11.09
#_#_
.TE
.EQ I
delim ##
.EN
It is important to understand that:
.EQ I
FC sub S =~~ FC sub B over { ( 1 - m% ) }
tf
FC sub B =~~ FC sub S times ( 1 - m% ) 
.EN
.KS
It is then easy to move back and forwards between the adjusted values and
unadjusted values by making use of this information. If we had the value
\[Po]10.76, for the fixed costs per unit, we can adjust for the mortality by
dividing by #(1 - m%)#.
.EQ I
FC sub S lm 10.76 over { ( 1 - m% ) }
.EN
.sp -0.6v
.EQ I
lineup =~~
10.76 over 0.97
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]11.09 ~per ^lamb
.EN
.KE
The technique works equally well with individual costs. Therefore, the
calculation to convert the mortality adjusted machinery costs back to its
unadjusted figure would be:
.EQ I
Machinery sub B lm Machinery sub S times ( 1 - m% ) 
.EN
.sp -0.6v
.EQ I
lineup =~~
3.78 times ( 1 - 0.03 )
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]3.67 ~per ^lamb
.EN
.
.XXXX 0 4 "Variable costs"
.LP
The variable costs are made of two components the costs of the acquired store
lamb and the daily cost of the weight added to the store lamb during the finishing
process.
.EQ I
"Variable costs" lm "Purchased weight" + "Originated weight"
.EN
.sp -0.6v
.EQ I
VC lineup =~~ PW + d(OW)
.EN
The calculation for the purchased weight is shown below based on the number of
lambs bought:
.EQ I
PW sub B lm
left ( "Store weight" times \[Po]/kg right ) + Vet + Transport 
.EN
.sp -0.6v
.EQ I
lineup =~~
left ( k sub s times P sub 1 right ) + v + t
.EN
.sp -0.6v
.EQ I
lineup =~~
left ( 30 times 1.5 right ) + 3 + 2
.EN
.sp -0.6v
.EQ I
lineup =~~
45 + 3 + 2 
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]50.00 ~per ^lamb
.EN
Unfortunately not all the lambs survive to be sold. The calculation for the
purchased weight is shown below based on the number of lambs sold and the
mortality rate of 3%:
.EQ I
PW sub S lm PW sub B + MC
.EN
.sp -0.6v
.EQ I
lineup =~~
PW sub B + m%(cd)
.EN
.sp -0.6v
.EQ I
lineup =~~
50.00 + 0.03(15)
.EN
.sp -0.6v
.EQ I
lineup =~~
50.00 + 0.45
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]50.45 ~per ^lamb
.EN
It can be seen above that the mortality increases the costs. If all of the
target lambs were to die before being sold, you would suffer not only the loss
of purchasing the lambs but also the additional cost of disposing of the fallen
stock at \[Po]15 per head. On 3,000 lambs a potential additional cost of
\[Po]45,000. It is assumed the transport cost covers the movement of the lamb
dead or alive off the property.
.LP
The calculation for the weight gain is shown below:
.EQ I
d(OW) lm "Days on farm"
times ( Financing + Fuel + Repair + Maintenance + Forage + Hay )
.EN
.sp -0.6v
.EQ I
lineup =~~
d ( fsl + fl + rp + mn + fo + hy )
.EN
.KS
First we must calculate the costs per head per day. We are going to do this as
before based on both the number of lambs that were bought as store and the
number of lambs that are actually sold.
The calculations based on the number of lambs bought:
.EQ I
fsl sub b =~~
{ ("Purchase price") ("Store kg") times Interest% } over 365 
=~~
{ P sub 1 ( k sub s ) times i% } over 365
=~~
{ 1.5(30) times 0.1 } over 365
=~~
0.01233 ^\[Po]/hd
.EN
.
.EQ I
fl sub b =~~
{Fuel } 
over { "Number of lambs bought" times "Days on farm" }
=~~
fl over { Q sub B times d }
=~~
{ 953 } over { 3,000 times 81 }
=~~
0.00392 ^\[Po]/hd \(dd
.EN
.FS
\(dd The large number of decimal places is not an attempt at accuracy nor is it
necessary as there are only 100 pence in the pound and huge amounts of
uncertainty in the expected values. However, I wanted the numbers which have
been adjusted for mortality to match those which have not been adjusted at the
end of this section. To establish the values for our target of 3,000 sheep will
require multiplying the values by both 81 and 3,000 which is 243,000. 1 divided
by 243,000 is 0.000004. So a large number of decimal places is unfortunately
required for this exercise.
.FE
.
.EQ I
rp sub b =~~
{"EAC Repair" } 
over { "Number of lambs bought" times "Days on farm" }
=~~
rp over { Q sub B times d }
=~~
{ 1,700 } over { 3,000 times 81 }
=~~
0.00700 ^\[Po]/hd
.EN
.
.EQ I
mn sub b =~~
{"EAC Maintenance" } 
over { "Number of lambs bought" times "Days on farm" }
=~~
mn over { Q sub B times d }
=~~
{ 1,000 } over { 3,000 times 81 }
=~~
0.00412 ^\[Po]/hd
.EN
.
.EQ I
fo sub b =~~ { "ha forage" times "\[Po]/ha" }
over { "Number of lambs bought" times "Days on farm" }
=~~
fo over { Q sub B times d }
=~~
{ 45 times 300 } over { 3,000 times 81 }
=~~
0.05556 ^\[Po]/hd
.EN
.
.EQ I
hy sub b =~~ { "Tonnes hay" times "\[Po]/tonne" }
over { "Number of lambs bought" times "Days on farm" }
=~~
hy over { Q sub B times d }
=~~
{ 177 times 50 } over { 3,000 times 81 }
=~~
0.03642 ^\[Po]/hd
.EN
.KE
The calculations can be done using the number lambs sold #Q sub S#. The number
of lambs sold is equal to the number of lambs bought multiplied by #1 -
"mortality rate"#.
.EQ I
Q sub S =~~ Q sub b ( 1 - m%) =~~ 3,000( 1 - 0.03) = 2,910
.EN
The calculations are then as follows:
.EQ I
fsl sub s =~~
{ ("Purchase price") ("Store kg") times Interest% }
over { 365 (1 - Mortality%)\(dg } 
=~~
{ P sub 1 ( k sub s ) times i% } over { 365 ( 1 - m%) }
=~~
{ 1.5(30) times 0.1 } over 354
=~~
0.01271 ^\[Po]/hd
.EN
.FS
\(dg This equations has been simplified. In symbols the equation is:
.EQ I
{ { P sub 1 ( k sub s ) times i% times Q sub B} over 365 }
over { Q sub B ( 1 - m% ) }
=~~
{ P sub 1 ( k sub s ) times i% times Q sub B }
over
{ 365 ( Q sub B ) ( 1 - m% ) }
=~~
{ P sub 1 ( k sub s ) times i% }
over
{ 365 ( 1 - m% ) }
.EN
.FE
.
.EQ I
fl sub s =~~
{Fuel } 
over { "Number of lambs sold" times "Days on farm" }
=~~
fl over { Q sub S times d }
=~~
{ 953 } over { 2,910 times 81 }
=~~
0.00404 ^\[Po]/hd
.EN
.
.EQ I
rp sub s =~~
{"EAC Repair" } 
over { "Number of lambs sold" times "Days on farm" }
=~~
rp over { Q sub S times d }
=~~
{ 1,700 } over { 2,910 times 81 }
=~~
0.00721 ^\[Po]/hd
.EN
.
.EQ I
mn sub s =~~
{"EAC Maintenance" } 
over { "Number of lambs sold" times "Days on farm" }
=~~
rp over { Q sub S times d }
=~~
{ 1,000 } over { 2,910 times 81 }
=~~
0.00424 ^\[Po]/hd
.EN
.
.EQ I
fo sub s =~~
{ "ha forage" times "\[Po]/ha" }
over { "Number of lambs sold" times "Days on farm" }
=~~
fo over { Q sub S times d }
=~~
{ 45 times 300 } over { 2,910 times 81 }
=~~
0.05727 ^\[Po]/hd
.EN
.
.EQ I
hy sub s =~~
{ "Tonnes hay" times "\[Po]/tonne" }
over { "Number of lambs sold" times "Days on farm" }
=~~
hy over { Q sub S times d }
=~~
{ 177 times 50 } over { 2,910 times 81 }
=~~
0.03755 ^\[Po]/hd
.EN
The calculations above show the impact of the mortality rate on the costs.
.KS
The variable costs per lamb can now be calculated with and without an
adjustment for mortality:
.EQ I
VC sub B lm
PW sub B + d( OW sub B )
.EN
.sp -0.6v
.EQ I
lineup =~~
PW sub B + d ( fsl sub b + fl sub b + rp sub b + mn sub b + fo sub b + hy sub b )
.EN
.sp -0.6v
.EQ I
lineup =~~
50.00 +  d ( 0.01233 + 0.00392 + 0.00700 + 0.00412 + 0.05556 + 0.03642 )
.EN
.sp -0.6v
.EQ I
lineup =~~
50.00 + d (0.11935)
.EN
.KE
.
.EQ I
VC sub S lm
PW sub S + d ( OW sub S )
.EN
.sp -0.6v
.EQ I
lineup =~~
left [ PW sub B + MC ]  + d ( OW sub S )
.EN
.sp -0.6v
.EQ I
lineup =~~
left [ PW sub B + m%(cd) right ] 
+ d ( fsl sub s + fl sub s + rp sub s + mn sub s + fo sub s + hy sub s )
.EN
.sp -0.6v
.EQ I
lineup =~~
left [ 50.00 + 0.03(15) right ]
+ d ( 0.01271 + 0.00404 + 0.00721 + 0.00424 + 0.05727 + 0.03755 )
.EN
.sp -0.9v
.EQ I
lineup =~~
left [ 50.00 + 0.45 right ]  + d (0.12302)
.EN
.sp -0.6v
.EQ I
lineup =~~
50.45 + d (0.12302)\(dg
.EN
.FS
\(dg If you image a graph with the cost on the y axis and days on the x axis
then #y = 50.45 + x(0.12302)#. This can be rearranged as #y = x(0.12302) + 50.45#
and now conforms to the standard form for the equation of a straight line #mx +
b# where #m# represents the slope of the line and #b# the intercept with the y
axis. In short each extra day the lamb spends on the farm costs 12.30 pence.
.FE
Again it is important to understand that:
.EQ I
d ( OW sub S ) =~~ { d ( OW sub B ) } over { ( 1 - m% ) } 
~~~tf~~~
d ( OW sub B ) =~~
d ( OW sub S )  times ( 1 - m% ) 
.EN
Therefore the total daily costs per head before accounting for the mortality
rate can be found by multiplying the #0.1230# by #(1 - m%)# which equates to
#0.1230( 1 - 0.03 ) = 0.1193#.
.LP
What are the variable costs to keep a lamb for 81 days? There are now two
different equations for this calculation depending on whether you work with the
number of lambs bought or sold:
.EQ I
VC sub B lm
PW sub B + d ( OW sub B )
.EN
.sp -0.6v
.EQ I
lineup =~~
50.00 + d (0.11935)
.EN
or:
.EQ I
VC sub S lineup =~~
PW sub S + d ( OW sub S )
.EN
.sp -0.6v
.EQ I
lineup =~~
left [ PW sub B + MC right ]  + d ( OW sub S )
.EN
.sp -0.6v
.EQ I
lineup =~~
left [ 50.00 + 0.45 right ]  + d (0.12302)
.EN
.sp -0.6v
.EQ I
lineup =~~
50.45 + d ( 0.12302 )
.EN
We will complete the calculations using both equations based on our scenario of
81 days and then discuss what we have established:
.EQ I
VC sub B lm
50.00 + 81(0.11935)
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]59.667 ~per ^lamb
.EN
.EQ I
VC sub S lineup =~~
50.45 + 81(0.12302)
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]60.41 ~per ^lamb
.EN
.KS
The calculations can also be done on a individual basis if you are interested:
.EQ I
VC sub B lm
PW sub B + d ( OW sub B )
.EN
.sp -0.6v
.EQ I
lineup =~~
left [ left ( k sub s times P sub 1 right ) + v + t right ] 
+
d ( fsl sub b + fl sub b + rp sub b + mn sub b + fo sub b + hy sub b )
.EN
.sp -0.6v
.EQ I
lineup =~~
left [ 45 + 3 + 2 right ]
+  81 ( 0.01233 + 0.00392 + 0.00700 + 0.00412 + 0.05556 + 0.03642 )
.EN
.sp -0.6v
.EQ I
lineup =~~
left [ 45 + 3 + 2 right ]
+ ( 0.9987 + 0.3175 + 0.5670 + 0.3337 + 4.5004 + 2.9500 )
.EN
.sp -0.6v
.EQ I
lineup =~~
50.00 + 9.6673
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]59.67 ~per ^lamb
.EN
.KE
.
.EQ I
VC sub S lm
PW sub S + d ( OW sub S )
.EN
.sp -0.6v
.EQ I
lineup =~~
left [ PW sub B + MC right ]  + d ( OW sub S )
.EN
.sp -0.6v
.EQ I
lineup =~~
left [ left ( k sub s times P sub 1 right ) + v + t  
+ left ( m% times cd right ) right ]
+
d ( fsl sub s + fl sub s + rp sub s + mn sub s + fo sub s + hy sub s )
.EN
.sp -0.6v
.EQ I
lineup =~~
left [ 45 + 3 + 2 + 0.45 right ]
+  81 ( 0.01271 + 0.00404 + 0.00721 + 0.00424 + 0.05727 + 0.03755 )
.EN
.sp -0.6v
.EQ I
lineup =~~
left [ 45 + 3 + 2 + 0.45 right ]
+ ( 1.0295 + 0.3272 + 0.5840 + 0.3434 + 4.6389 + 3.0416 )
.EN
.sp -0.6v
.EQ I
lineup =~~
50.45 + 9.9646
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]60.415 ~per ^lamb
.EN
The totals for the individual costs can also be displayed in a table:
.EQ I
delim @@
.EN
.TS
tab (#) center;
l c c
l c c
l n n .
#_#_
#@VC sub B@#@VC sub S@
#_#_
Store lamb#\[Po]45.00#\[Po]45.00
Vet#\[Po]3.00#\[Po]3.00
Transport#\[Po]2.00#\[Po]2.00
#_#_#
Purchased weight#\[Po]50.00#\[Po]50.00
.sp 0.8
Mortality##\[Po]0.45
#_#_#
#\[Po]50.00#\[Po]50.45
.sp 0.8
Finance#\[Po]1.00#\[Po]1.03#
Fuel#\[Po]0.32#\[Po]0.33#
Repair#\[Po]0.57#\[Po]0.58#
Maintenance#\[Po]0.33#\[Po]0.34#
Forage#\[Po]4.50#\[Po]4.64#
Hay#\[Po]2.95#\[Po]3.04#
#_#_#
Originated weight#\[Po]\9.67#\[Po]9.96
.sp 0.8
#=#=
Total#\[Po]59.67#\[Po]60.41
#=#=
.TE
.EQ I
delim ##
.EN
The column on the right hand side of the table for #VC sub S# is not exactly
right. There is nothing wrong with the inherent logic, the problem lies in the
fact that when there are multiple lambs, the purchased weight and originated
weight are not multiplied by the same number. This should be clear by the end
of this section.
.LP
It is worth noting the difference between the cost of kilograms of purchased
weight vs originated weight:
.EQ I
PW =~~
PW over "Store kg"
=~~
50.45 over 30
=~~
1.68 ~\[Po]/kg 
.EN
.
.EQ I
d ( OW sub S ) =~~
{ d ( OW sub S ) }
over
{"Sale kg" - "Store kg" }
=~~
81(0.12302)
over
42-30
=~~
9.9646
over
12
=~~
0.83 ~\[Po]/kg
.EN
It can be seen from the above comparison that it is cheaper to originate
kilograms of live weight than it is to buy them. It is logical to deduce that
you therefore want to buy the lightest lamb that will make the growth rate.
Also if the price of the store lamb per kilogram falls below your cost of
originating the kilograms, for the same specification of lamb, you want to buy
the heaviest lambs available.  At the end of this chapter there is a small
amount of information on growth rates.
.LP
If you want to know the total variable cost you might be tempted to multiply
the variable costs by the appropriate quantity of lambs as show below, this
will only be half right!
.EQ I
TVC sub B lm Q sub B ( VC sub B )
.EN
.sp -0.6v
.EQ I
lineup =~~
Q sub B left [ (PW sub B ) + d ( OW sub B ) right ]
.EN
.sp -0.6v
.EQ I
lineup =~~
3,000 left [ 50.00 + 81 ( 0.11935 ) right ]
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]179,002
.EN
or:
.EQ I
TVC sub S lm Q sub S ( VC sub S )
.EN
.sp -0.6v
.EQ I
lineup =~~
Q sub S left [ (PW sub S ) + d ( OW sub S ) right ]
.EN
.sp -0.6v
.EQ I
lineup =~~
2,910 left [ 50.45 + 81 ( 0.12302 ) right ]
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]175,807
.EN
The result is somewhat absurd. The figure that does not include a mortality
charge is greater than the figure than does include the mortality charge.  The
purchase costs are occurred when the lamb is bought regardless of whether it
lives to be sold. We can now adjust the #TVC sub S# to reflect the fact that
the purchase and mortality cost should be calculated with the number of lambs
bought.
.EQ I
TVC sub S =~~ Q sub B (PW sub S ) + d ( OW sub S ) Q sub S   
.EN
.KS
You can now see that the purchased cost is multiplied by the number of lambs
before adjusting for the mortality rate in both instances. We will redo the
calculations with a little more detail:
.EQ I
TVC sub B lm Q sub B left [ (PW sub B ) + d ( OW sub B ) right ]
.EN
.sp -0.6v
.EQ I
lineup =~~
Q sub B left {  
left [ left ( k sub s times P sub 1 right ) + v + t right ] 
+
left [ 
d ( fsl sub b + fl sub b + rp sub b + mn sub b + fo sub b + hy sub b )
right ]
right } 
.EN
.sp -0.6v
.EQ I
lineup =~~
3,000 left { left [ 45 + 3 + 2 right ]
+ left [ +  81 ( 0.01233 + 0.00392 + 0.00700 + 0.00412 + 0.05556 + 0.03642 )
right }
.EN
.sp -0.6v
.EQ I
lineup =~~
3,000 left { left [ 45 + 3 + 2 right ]
+ left [ 0.9987 + 0.3175 + 0.5670 + 0.3337 + 4.5004 + 2.9500 ) ] right }
.EN
.sp -0.6v
.EQ I
lineup =~~
left [ 135,000 + 9,000 + 6,000 right ]
+ left [ 2,996 + 953 + 1,701 + 1,001 + 13,501 + 8,850  right ]
.EN
.sp -0.6v
.EQ I
lineup =~~
150,000 + 29,002
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]179,002
.EN
.KE
.
.EQ I
TVC sub S lm Q sub B (PW sub S ) + d ( OW sub S ) Q sub S  
.EN
.sp -0.6v
.EQ I
lineup =~~ Q sub B left ( PW sub B + MC right ) + d ( OW sub S ) Q sub S  
.EN
.sp -0.6v
.EQ I
lineup =~~ Q sub B ( PW sub B )
+ Q sub B ( MC ) + d ( OW sub S ) Q sub S  
.EN
.sp -0.6v
.EQ I
lineup =~~
Q sub B
left [ left ( k sub s times P sub 1 right ) + v + t right ]
+ Q sub B ( m% times cd ) 
+
Q sub S left [ 
d ( fsl sub s + fl sub s + rp sub s + mn sub s + fo sub s + hy sub s )
right ]
.EN
.sp -0.6v
.EQ I
lineup =~~
3,000 left [ 45 + 3 + 2 right ]
+ 3,000 left [ 0.45 right ]
.EN
.sp -0.6v
.EQ I
lineup {hphantom { =~~} } 
+ 2,910 left [  81 ( 0.01271 + 0.00404 + 0.00721 + 0.00424 + 0.05727 + 0.03755 ) right ]
.EN
.sp -0.6v
.EQ I
lineup =~~
3,000 left [ 45 + 3 + 2 right ] + 3,000 left [ 0.45 right ]
.EN
.sp -0.6v
.EQ I
lineup {hphantom { =~~} } 
+ 2,910 left [ 1.0295 + 0.3272 + 0.5840 + 0.3434 + 4.6389 + 3.0416  right ]
.EN
.sp -0.6v
.EQ I
lineup =~~
left [ 135,000 + 9,000 + 6,000 right ] + left [ 1,350 right ]
+ left [ 2,996 + 953 + 1,701 + 1,001 + 13,501 + 8,850  right ]
.EN
.sp -0.6v
.EQ I
lineup =~~
150,000 + 1,350 + 29,002
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]180,352
.EN
It can be seen that both methods yield the same result for the daily costs of
originating the weight on farm which is a natural consequence of the mortality
adjusted costs being multiplied by the mortality adjusted quantity. In essence
for a total output of 3,000 lambs, in this instance, the total of the daily
costs are \[Po]29,002. The mortality rate causes this cost to be spread over
fewer lambs. This means that the cost apportioned to each surviving lamb is
greater than that which would be apportioned to all the store lambs, that
were bought. had they survived. The total variable costs must equal the value
of \[Po]29,002 regardless of how they are apportioned.
.LP
We can symbolically resolve the formula for the total variable costs based on
the lambs sold, back to the lambs bought. This shows that the total variable
cost for the lambs sold is equal to the total variable cost for the lambs
bought plus the impact of mortality.
.EQ I
TVC sub S lm Q sub B (PW sub S ) + d ( OW sub S ) Q sub S  
.EN
.sp -0.6v
.EQ I
lineup =~~ Q sub B left ( PW sub B + MC right ) + d ( OW sub S ) Q sub S  
.EN
.sp -0.6v
.EQ I
lineup =~~ Q sub B ( PW sub B ) + Q sub B ( MC ) + d ( OW sub S ) Q sub S  
.EN
.sp -0.6v
.EQ I
lineup =~~ Q sub B (MC) + left [ Q sub B (PW sub B ) + d ( OW sub S ) Q sub S right ]
.EN
.sp -0.6v
.EQ I
lineup =~~
Q sub B (MC) + left [ Q sub B (PW sub B ) + d ( OW sub S ) Q sub B ( 1 - m%) right ]
.EN
.sp -0.6v
.EQ I
lineup =~~
Q sub B (MC) + Q sub B  left [ PW sub B + d ( OW sub S ) ( 1 - m%) right ] 
.EN
.sp -0.6v
.EQ I
lineup =~~
Q sub B (MC) + Q sub B  left [ PW sub B + { d ( OW sub B ) } over { ( 1 - m% ) }
( 1 - m%) right ] 
.EN
.sp -0.6v
.EQ I
lineup =~~
Q sub B (MC) + Q sub B  left [ PW sub B + d ( OW sub B ) right ] 
.EN
.sp -0.6v
.EQ I
lineup =~~
Q sub B (MC) + TVC sub B
.EN
.sp -0.6v
.EQ I
lineup =~~
3,000 (0.45) + 179,002
.EN
.sp -0.6v
.EQ I
lineup =~~
1,350 + 179,002
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]180,352
.EN
.KS
The totals for the individual costs can also be displayed in a table as shown
below:
.EQ I
delim @@
.EN
.TS
tab (#) center;
l c c
l c c
l n n .
#_#_
#@TVC sub B@#@TVC sub S@
#_#_
Store lamb#\[Po]135,000#\[Po]135,000
Vet#\[Po]9,000#\[Po]9,000
Transport#\[Po]6,000#\[Po]6,000
#_#_#
Purchased weight#\[Po]150,000#\[Po]150,000
.sp 0.8
Mortality##\[Po]1,350
#_#_#
#\[Po]150,000#\[Po]151,350
.sp 0.8
Finance#\[Po]2,996#\[Po]2,996#
Fuel#\[Po]953#\[Po]953#
Repair#\[Po]1,701#\[Po]1,701#
Maintenance#\[Po]1,001#\[Po]1,001#
Forage#\[Po]13,501#\[Po]13,501#
Hay#\[Po]8,850#\[Po]8,850#
#_#_#
Originated weight#\[Po]\29,002#\[Po]29,002
.sp 0.8
#=#=
Total#\[Po]179,002#\[Po]180,352
#=#=
.TE
.EQ I
delim ##
.EN
.KE
It can be seen above, that the largest component of the variable cost is the
purchase of the store lamb. The store lamb purchase represents, in this
scenario, 75% of the total variable costs based on the number of lambs sold.
The store lamb, forage and hay represents 88% of the total variable costs.
.LP
The price paid for the store lamb is critical to the success of the enterprise.
This is logical because you usually purchase more kilograms than you originate.
If a lamb is purchased weighing 30 kg and sold at 42 kg the originated weight
of 12 kg represents 29% of the finished weight, the remaining weight was
purchased.
.LP
You may also have noticed the following:
.EQ I
VC sub TB =~~
TVC sub B over Q sub B 
=~~
179,002
over
3,000
=~~
\[Po]59.67 ~per ^lamb
.EN
and:
.EQ I
VC sub TS =~~
=~~
TVC sub S over Q sub S
=~~
180,352
over
2,910
=~~
\[Po]61.98 ~per ^lamb
.EN
.KS
We will break down the equation #VC sub TS# to see how to calculate the costs
at the individual level.
.EQ I
VC sub TS lm
TVC sub S over Q sub S 
.EN
.sp -0.6v
.EQ I
lineup =~~
{ Q sub B  left [ PW sub B  + MC  right ]
+ d ( OW sub S ) Q sub S }
over 
Q sub S
.EN
.sp -0.6v
.EQ I
lineup =~~
{ Q sub B  left [ PW sub B  + MC  right ]
+ d ( OW sub S ) Q sub B ( 1 - m% ) }
over 
Q sub S
.EN
.sp -0.6v
.EQ I
lineup =~~
{ Q sub B  left [ PW sub B  + MC + d ( OW sub S ) ( 1 - m% ) right ] }
over 
Q sub S
.EN
.sp -0.6v
.EQ I
lineup =~~
{ Q sub B  left [ PW sub B  + MC
+ { d ( OW sub B ) } over { ( 1 - m% ) } ( 1 - m% ) right ] }
over 
Q sub S
.EN
.sp -0.6v
.EQ I
lineup =~~
{ Q sub B  left [ PW sub B  + MC + d ( OW sub B ) right ] }
over 
Q sub S
.EN
.sp -0.6v
.EQ I
lineup =~~
{ Q sub B  left [ PW sub B  + MC + d ( OW sub B ) right ] }
over 
{ Q sub B ( 1 - m% ) }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ left [ PW sub B  + MC + d ( OW sub B ) right ] }
over 
{ ( 1 - m% ) }
.EN
.KE
This can be further simplified to:
.EQ I
lineup =~~
{ MC + VC sub B }
over 
{ ( 1 - m% ) }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ 0.45 + 59.67 }
over 
{ ( 1 - 0.03 ) }
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]61.98 ~per ^lamb
.EN
.KS
It can also be written as:
.EQ I
lineup =~~
{ PW sub B  + MC }
over 
{ ( 1 - m% ) }
+
{ d ( OW sub B ) }
over 
{ ( 1 - m% ) }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ PW sub B + MC }
over 
{ ( 1 - m%) }
+
d ( OW sub S ) 
.EN
.sp -0.6v
.EQ I
lineup =~~
{ PW sub S }
over 
{ ( 1 - m%) }
+ d ( OW sub S ) 
.EN
.sp -0.6v
.EQ I
lineup =~~
50.45
over { 1 - 0.03 }
+ 9.97
.EN
.sp -0.6v
.EQ I
lineup =~~
52.01 + 9.97
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]61.98 ~per ^lamb
.EN
.KE
This discovery makes life simple as we can now account for the mortality rate
by simply dividing all the values established using the quantity bought #VC sub
B# by #1 - mortality%#.
.KS
The mortality costs can also be stated as: 
.EQ I
m%(cd) over { 1 - m% } 
~~~tf~~~
m% over { 1 - m% } times cd
.EN
Which equates to:
.EQ I
0.03 over { 1 - 0.03 } times 15
=~~
0.03093 times 15
=~~
\[Po]0.464
.EN
.KE
We can now complete a table to show the costs:
.EQ I
delim @@
.EN
.TS
tab (#) center;
l c c
l c c
l n n .
#_#_
#@VC sub TS@#@VC sub TS@
#_#_
Store lamb#\[Po]45.00#\[Po]46.39
Vet#\[Po]3.00#\[Po]3.09
Transport#\[Po]2.00#\[Po]2.06
#_#_#
Purchased weight#\[Po]50.00#\[Po]51.55
.sp 0.8
Mortality#\[Po]0.45#\[Po]0.46
#_#_#
#\[Po]50.45#\[Po]52.01
.sp 0.8
Finance#\[Po]1.00#\[Po]1.03#
Fuel#\[Po]0.32#\[Po]0.33#
Repair#\[Po]0.57#\[Po]0.58#
Maintenance#\[Po]0.33#\[Po]0.34#
Forage#\[Po]4.50#\[Po]4.64#
Hay#\[Po]2.95#\[Po]3.04#
#_#_#
Originated weight#\[Po]\9.67#\[Po]9.97
.sp 0.5
#_#_#
#\[Po]60.12#\[Po]61.98
.sp 0.5
.T&
l l n
l n n .
Multiplier\(dg#1.0309
.sp 0.8
#=#=
Total#\[Po]61.98#\[Po]61.98
#=#=
.TE
.EQ I
delim ##
.EN
.FS
\(dg The multiplier is the reciprocal of the mortality. #1 over { 1 - m% } = 1
over { 1 - 0.03 } = 1.0309#
.FE
To clarify, the equation for the variable costs per lamb sold is best expressed
as:
.EQ I
VC sub TS =~~
{ left [ PW sub B  + MC + d ( OW sub B ) right ] }
over 
{ ( 1 - m% ) }
.EN
.KS
This equation can be further simplified, if desired, as we have demonstrated.
If we multiply the total variable costs per unit sold # VC sub TS # by the
quantity bought # Q sub S # we also logically arrive at the total cost # TVC
sub S#:
.EQ I
TVC sub S lm 
VC sub TS times Q sub S
.EN
.sp -0.6v
.EQ I
lineup =~~
{ left [ PW sub B  + MC + d ( OW sub B ) right ] }
over 
{ ( 1 - m% ) } times Q sub S
.EN
.sp -0.6v
.EQ I
lineup =~~
{ left [ PW sub B  + MC + d ( OW sub B ) right ] }
over 
{ ( 1 - m% ) } times Q sub B ( 1 - m%)
.EN
.sp -0.6v
.EQ I
lineup =~~
left [ PW sub B  + MC + d ( OW sub B ) right ]
times Q sub B
.EN
.EQ I
lineup =~~
left [ MC + VC sub B right ]
times Q sub B
.EN
.KE
.KS
The transformation informs us that the total variable costs based on the
lambs sold can also be expressed in terms of the lambs bought.
.EQ I
VC sub TS times Q sub S lm ( MC + VC sub B ) times Q sub B
.EN
.sp -0.6v
.EQ I
61.98(2,910) 
lineup =~~
(0.45 + 59.67)(3,000)
.EN
.sp -0.6v
.EQ I
\[Po]180,362
lineup =~~
\[Po]180,360
.EN
.KE
.
.XXXX 0 4 "Total costs"
.LP
The total costs can be represented with the generalised equation below:
.EQ I
"Total costs" lm
"Fixed costs" + "Variable costs" times Quantity
.EN
.sp -0.6v
.EQ I
"TC" lineup =~~
FC + VC(Q)
.EN
Calculate the total costs, given the purchase of 3,000 lambs kept on farm for
81 days. We will use the costs we have already calculated to save effort.
.EQ I
"TC" lm
FC + [ VC sub TS ] Q sub S
.EN
.sp -0.6v
.EQ I
lineup =~~
 FC + { left [ PW sub B + MC + d(OW sub B ) right ] }
over 
{ ( 1 - m% ) }
times Q sub B ( 1 - m% )
.EN
.sp -0.6v
.EQ I
lineup =~~
 FC + left [ PW sub B + MC + d(OW sub B ) right ]
times
Q sub B
.EN
.sp -0.6v
.EQ I
lineup =~~
 FC + left [ PW sub B + MC + d(OW sub B ) right ]
times
Q sub B
.EN
.sp -0.6v
.EQ I
lineup =~~
32,272 + left [ 50.00 + 0.45 + 81(0.11935)  right ] times 3,000
.EN
.sp -0.6v
.EQ I
lineup =~~
32,272 + left [ 50.00 + 0.45 + 9.6674  right ] times 3,000
.EN
.sp -0.6v
.EQ I
lineup =~~
32,272 + 150,000 + 1,350 + 29,002
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]212,624
.EN
Above is a case where the total variable costs in terms of the lambs sold,
resolves to a multiplication in terms of the lambs bought.
.KS
The total cost can also be broken down into its individual components from the
values we have previously calculated:
.TS
tab (#) center;
l c c 
l c c
l n n .
#_
#TC#
#_#
Labour#\[Po]12,000
Machinery#\[Po]11,000
Hire#\[Po]2,000
Finance#\[Po]1,272
Property & rents#\[Po]6,000
#_#
Fixed costs#\[Po]32,272#16%
.sp 0.8
Store lamb#\[Po]135,000
Vet#\[Po]9,000#
Transport#\[Po]6,000#
#_#
Purchased weight#\[Po]150,000
.sp 0.8
Mortality#\[Po]1,350#
#_#
#\[Po]151,350#71%
.sp 0.8
Finance#\[Po]2,996#
Fuel#\[Po]953#
Repair#\[Po]1,701#
Maintenance#\[Po]1,001#
Forage#\[Po]13,501#
Hay#\[Po]8,850#
#_
Originated weight#\[Po]29,002#13%
.sp 0.8
#=
Total#\[Po]212,624
#=
.TE
.KE
It can be seen in the scenario above that the largest component of the total
costs is the purchase of the lambs including the impact of the mortality, at
71% of the total costs. The labour, machinery, store lamb, forage and hay
represent 85% of the total costs.
.LP
To establish the costs per store lamb bought, divide by the quantity #Q sub B#:
.EQ I
TC sub TB lm
{ FC + [ VC sub TS ] Q sub S }
over Q sub B
.EN
.sp -0.6v
.EQ I
lineup =~~
{ FC + { left [ PW sub B + MC + d(OW sub B ) right ] }
over 
{ ( 1 - m% ) }
times Q sub B ( 1 - m% )
}
over Q sub B
.EN
.sp -0.6v
.EQ I
lineup =~~
{ FC + { left [ PW sub B + MC + d(OW sub B ) right ] } times Q sub B }
over Q sub B
.EN
.sp -0.6v
.EQ I
lineup =~~
FC over Q sub B
+
{ left [ PW sub B + MC + d(OW sub B ) right ] times Q sub B }
over Q sub B
.EN
.sp -0.6v
.EQ I
lineup =~~
FC over Q sub B
+
left [ PW sub B + MC + d(OW sub B ) right ]
.EN
.sp -0.6v
.EQ I
lineup =~~
32,272 over 3,000 + [ 50.00 + 0.45 + 9.6674 ]
.EN
.sp -0.6v
.EQ I
lineup =~~
10.76 + 60.12
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]70.88 ~per ^lamb
.EN
.KS
To establish the costs per store lamb sold, divide by the quantity #Q sub S#:
.EQ I
TC sub TS lm
{ FC + [ VC sub TS ] Q sub S }
over Q sub S
.EN
.sp -0.6v
.EQ I
lineup =~~
{ FC + { left [ PW sub B + MC + d(OW sub B ) right ] }
over 
{ ( 1 - m% ) }
times Q sub B ( 1 - m% )
}
over Q sub S
.EN
.sp -0.6v
.EQ I
lineup =~~
{ FC + { left [ PW sub B + MC + d(OW sub B ) right ] } times Q sub B }
over Q sub S
.EN
.sp -0.6v
.EQ I
lineup =~~
{ FC + { left [ PW sub B + MC + d(OW sub B ) right ] } times Q sub B }
over { Q sub B ( 1 - m% ) }
.EN
.sp -0.6v
.EQ I
lineup =~~
FC 
over { Q sub B ( 1 - m% ) }
+
{ left [ PW sub B + MC + d(OW sub B ) right ] times Q sub B }
over { Q sub B ( 1 - m% ) }
.EN
.sp -0.6v
.EQ I
lineup =~~
FC 
over { Q sub B ( 1 - m% ) }
+
{ left [ PW sub B + MC + d(OW sub B ) right ] }
over { ( 1 - m% ) }
.EN
.sp -0.6v
.EQ I
lineup =~~
32,272 over { 3,000( 1 - 0.03) }
+ { [ 50.00 + 0.45 + 9.6674 ] } over { ( 1 - 0.03 ) }
.EN
.sp -0.6v
.EQ I
lineup =~~
11.09 + 61.98
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]73.07 ~per ^lamb
.EN
.KE
Again this can be broken down into the constituent parts based on our previous
work:
.EQ I
delim @@
.EN
.TS
tab (#) center;
l c c
l c c
l n n .
#_#_
#@TC sub TB@#@TC sub TS@
#_#_
Labour#\[Po]4.00#\[Po]4.12
Machinery#\[Po]3.67#\[Po]3.78
Hire#\[Po]0.67#\[Po]0.69
Finance#\[Po]0.42#\[Po]0.33
Property & rents#\[Po]2.00#\[Po]2.06
#_#_#
Unit fixed costs#\[Po]10.76#\[Po]11.09
.sp 0.8
Store lamb#\[Po]45.00#\[Po]46.39
Vet#\[Po]3.00#\[Po]3.09
Transport#\[Po]2.00#\[Po]2.06
#_#_#
Purchased weight#\[Po]50.00#\[Po]51.55
.sp 0.8
Mortality#\[Po]0.45#\[Po]0.46
#_#_#
#\[Po]50.45#\[Po]52.01
.sp 0.8
Finance#\[Po]1.00#\[Po]1.03#
Fuel#\[Po]0.32#\[Po]0.33#
Repair#\[Po]0.57#\[Po]0.58#
Maintenance#\[Po]0.33#\[Po]0.34#
Forage#\[Po]4.50#\[Po]4.64#
Hay#\[Po]2.95#\[Po]3.04#
#_#_#
Originated weight#\[Po]\9.67#\[Po]9.97
.sp 0.8
#=#=
Total#\[Po]70.88#\[Po]73.07
#=#=
.TE
.EQ I
delim ##
.EN
.
.XXXX 0 4 "Cost per kg DM"
.LP
The feed costs are shown below:
.EQ I
Forage =~~
"Establishment cost \[Po]/ha" over DM sub ha
=~~
\[Po]300
over 
{ 50,000 times 0.135 times 0.8 }
=~~
\[Po]300 over 5,400
=~~
0.056 ~\[Po]/kg^DM
.EN
.
.EQ I
Hay
=~~
"\[Po]/tonne"
over
{ 1,000 times DM% times Utilisation }
=~~
\[Po]50
over 
{ 1,000 times 0.85 times 0.7 }
=~~
\[Po]50 over 595
=~~
0.084 ~\[Po]/kg^DM
.EN
It can be seen above that the hay is more expensive per kilogram of dry matter.
The low utilisation rate with the hay is a concern as the total usable dry
matter is only 595 kg per tonne. The feed costs can also be used in conjunction
with the cumulative calculation for the dry matter to establish the cost of
feeding the lamb.
.EQ I
"Feed cost" lm
DM sub d times %Diet times \[Po]/kg
.EN
.sp -0.6v
.EQ I
lineup =~~
d over 2 left [ k sub s + k sub f  right ] %bw times %Diet times \[Po]/kg
.EN
The feed costs for a lamb purchased at 30 kg and finished at 42 kilograms over
81 days, if we assume that 70% of the diet is turnips and the remaining 30%
hay, would be as follows.
.EQ I
Forage lineup =~~
d over 2 left [ k sub s + k sub f  right ] %bw times %Diet times \[Po]/kg
.EN
.sp -0.6v
.EQ I
lineup =~~
81 over 2 left [ 42 + 30  right ] 0.04 times 0.7 times 0.056
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]4.57 ~per ^lamb
.EN
.EQ I
Hay lineup =~~
d over 2 left [ k sub s + k sub f  right ] %bw times %Diet times \[Po]/kg
.EN
.sp -0.6v
.EQ I
lineup =~~
81 over 2 left [ 42 + 30  right ] 0.04 times 0.3 times 0.084
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]2.94 ~per ^lamb
.EN
This gives a total cost of # \[Po]4.57 + \[Po]2.94 = \[Po]7.51 ~per ^lamb #. We
have previously calculated the feed costs as:
.EQ I
Forage =~~ fo sub b =~~ 0.05556 ^\[Po]/hd
.EN
.sp -0.6v
.EQ I
Hay =~~ hy sub b =~~ 0.03642 ^\[Po]/hd
.EN
If #fo sub b# and #hy sub b# were multiplied by the number of days, 81, we
would get \[Po]4.50 and \[Po]2.95 respectively giving a total of # \[Po]7.45
~per ^lamb #. The two methods should yield approximately the same values with
in the same system, that is a combination of roots and hay in this instance.
The method in this section is useful to know in case you are interested in
analysing the feed costs across different systems. Growth rates are dependent
on the quality and quantity of feed and cheap grass with a low energy content
will result in low growth rates and longer finishing periods which may not be
as cost effective as more expensive feed with higher growth rates.
.
.XXXX 0 3 "Revenue, profit & breakeven"
.LP
In this section we will use the costs we have established to examine revenue,
profit and the way the breakeven formula can be manipulated.
.
.XXXX 0 4 "Revenue"
.LP
The revenue can be expressed as:
.EQ I
Revenue sub unit lm "Sale price after deductions" times "Finished kilograms"
.EN
The finished kilograms can be expressed with the formula below:
.EQ I
"Finished kilograms" lm
"Store weight" + ( "Days on farm" - 1 )  times ("growth rate")
.EN
.sp -0.6v
.EQ I
k sub f lineup =~~
k sub s + ( d -1 )r
.EN
.KS
The sale price after any marketing expenses can be expressed with the formula
below:
.EQ I
"Sale price after marketing" lm
"Sale price before deductions"
times ( 1 - "marketing expense%")
.EN
.sp -0.6v
.EQ I
P sub 3 lineup =~~
P sub 2 ( 1 - c%)
.EN
.KE
The complete formula can now be expressed with symbols as:
.EQ I
R sub U =~~
P sub 2 ( 1 - c%) times left [ k sub s + ( d - 1 )r right ]
.EN
We can now establish the theoretical revenue from store lamb purchased at a
weight of 30 kg and fattened for 81 days with a weight gain of 0.15 kg per day,
after which it was sold at \[Po]2.10 per kg. The marketing costs are 3% of the
sale price.
.EQ I
R sub U lm
P sub 2 ( 1 - c%) times  left [ k sub s + ( d - 1 )r right ] 
.EN
.sp -0.6v
.EQ I
lineup =~~
2.10 ( 1 - 0.03 ) times left [ 30 + (81 - 1 )0.15 right ] 
.EN
.sp -0.6v
.EQ I
lineup =~~
2.037 times left [ 30 + 12 right ] 
.EN
.sp -0.6v
.EQ I
lineup =~~
2.037 times left [ 42 right ] 
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]85.55 ~per ^lamb
.EN
The price has been reduced from 2.10 \[Po]/kg to 2.037 \[Po]/kg due to the
sales commission. The formula above shows that the revenue is affected by a
number of factors. Some factors like the price are beyond the control of the
farmer but others, like the sales commission, weight of the store lamb and
growth rate can be impacted by the farmer's decisions.
.LP
We can use the information above to state the price after deductions:
.EQ I
P sub 3 lm  P sub 2 ( 1 - c%)
.EN
.sp -0.6v
.EQ I
lineup =~~
2.10 ( 1 - 0.03 )
.EN
.sp -0.6v
.EQ I
lineup =~~
2.037 ~\[Po]/kg
.EN
To calculate the total revenue, the kilograms must be multiplied by the number
of lambs to be sold:
.EQ I
"Total revenue " lm
Price times left [ "Finished kilograms" times Quantity right ]
.EN
.
.EQ I
TR lineup =~~ P sub 3 times ( k sub f ) Q sub S
.EN
.sp -0.6v
.EQ I
lineup =~~
P sub 3 times  left [ ( k sub s + ( d - 1 )r ) Q sub B ( 1 - m% ) right ]
.EN
.sp -0.6v
.EQ I
lineup =~~
2.037 times left [ 42 times 2,910 right ] 
.EN
.sp -0.6v
.EQ I
lineup =~~
2.037 times 122,220
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]248,962
.EN
It can be seen that the sale of 3,000 finished lambs equates to the sale of
122,220 kg at \[Po]2.037 per kg. The mortality rate has led to a reduction in
kilograms sold of 3,780 kg. This is the difference between 3,000 and 2,910
lambs multiplied by 42 kg, the target finishing weight. In monetary terms this
is a loss of cash of \[Po]7,700.  It is not possible to have a mortality rate
of zero but still it shows the impact of the mortality rate on the revenue
stream.
.
.XXXX 0 4 "Profit"
.LP
Profit is the revenue minus the cost and can be expressed as follows:
.EQ I
Profit sub unit lm Revenue sub unit - "Total costs" sub unit
.EN
In symbols this is represented as:
.EQ I
\[*p] sub u lineup =~~ R sub U - TC sub TS
.EN
.sp -0.6v
.EQ I
lineup =~~
85.55 - 73.07
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]12.48 ~per ^lamb
.EN
.KS
The total profit is expressed below:
.EQ I
Profit lm "Total revenue" - "Total costs"
.EN
.EQ I
\[*p] lineup =~~ TR - TC
.EN
.sp -0.6v
.EQ I
lineup =~~
248,962 - 212,624
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]36,338
.EN
.KE
As a side note, this profit was generated from 46 hectares of stubble turnips
giving a profit of \[Po]790 per hectare.
.
.XXXX 0 4 "Contribution"
.LP
The contribution is the difference between the revenue and the variable costs.
This contribution is the amount that each unit "contributes" towards the fixed
costs. Contribution can be expressed as:
.EQ I
Contribution sub unit =~~ Price sub unit - "Variable cost" sub unit
.EN
This can be expressed in symbols as:
.EQ I
C sub U
=~~ 
P sub 3 ( k sub f ) - VC sub TS
.EN
The unit in this instance is a lamb. The price of a lamb is a function of the
finished weight and the price achieved after deductions, in this instance the
marketing cost. We can then calculate the contribution based on the costs we
have previously calculated:
.EQ I
C sub U
lm
P sub 3 ( k sub f ) - VC sub TS
.EN
.sp -0.6v
.EQ I
lineup =~~
2.037(42) - 61.98
.EN
.sp -0.6v
.EQ I
lineup =~~
85.55 - 61.98
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]23.57 ~per ^lamb
.EN
The unit contribution can be broken down into its constituent parts:
.EQ I
C sub U lm
P sub 3 ( k sub f ) - VC sub TS
.EN
.sp -0.6v
.EQ I
lineup =~~ 
P sub 3 ( k sub f )
-
{ PW sub B + MC + d ( OW sub B ) } over {  1 - m%  }
.EN
.sp -0.6v
.EQ I
lineup =~~
P sub 2 ( 1 - c%) times left [ k sub s + (d - 1 )r right ]
- 
{ left [ ( k sub s times P sub 1 ) + v + t + ( m% times cd ) right ] 
+
left [ d ( fsl sub b + rp sub b + mn sub b + fo sub b + hy sub b ) right ] }
over 
{  1 - m% }
.EN
.
It can be seen above that the contribution is impacted by a large number of
inputs. However, we have previously stated that the store lamb #( k sub s times
P sub 1 )# represents 75% of the total variable cost. The store lamb #( k sub s
times P sub 1 )#, forage #fo# and hay #hy# represent 88% of the total variable
cost. Therefore the price paid for the store lamb, the price paid per tonne for
the hay and the fresh yield achieved on the forage crop will have a large
impact on the variable costs and the contribution.
.LP
We have previously demonstrated that a lower growth rate will lead to more feed
being consumed for a given weight gain and therefore more costs. Subsequently
higher growth rates and shorter days on farm are both preferable and more
profitable.
.LP
At a unit level it can also be seen that the mortality rate #m%# appears twice.
Once to cover the cost of disposing of a dead lamb and second as an increase in
the costs due to their being less lambs over which to spread the costs. The
third impact is as a lost sale which reduces the revenue as we have previously
discussed.
.
.XXXX 0 4 "Breakeven"
.LP
Breakeven is when the total revenue is equal to the total costs, that is to say
the profit is zero. The breakeven quantity can also be calculated using the
contribution and has previously been defined as:
.EQ I
Q =~~ FC over left ( P - VC right )
.EN
This can be expressed in words as:
.EQ I
Quantity =~~ "Fixed costs" over Contribution sub unit
.EN
.KS
Using the values from our prior calculations this would give:
.EQ I
Q sub S lm FC over C sub U
.EN
.sp -0.6v
.EQ I
lineup =~~
32,272 over 23.57
.EN
.sp -0.6v
.EQ I
lineup =~~
1,369 ~lambs
.EN
.KE
You must be aware that this is the quantity of lambs that must be \fBsold\fP.
The contribution and the revenue are logically based on the number of lambs
that are sold. To establish the number of lambs that you will need to purchase
to breakeven, you need to divide by #( 1 - mortality%)#.
.EQ I
Q sub B lm Q sub S over { ( 1 - m%) }
.EN
.sp -0.6v
.EQ I
lineup =~~
1,369 over { ( 1 - 0.03 ) }
.EN
.sp -0.6v
.EQ I
lineup =~~
1,412 ~lambs
.EN
.
.XXXX 0 5 "Breakeven - sale price per kg"
.LP
The breakeven sale price can be established by resolving for #P sub 2# which is
the sale price before the deduction of the sales commission. We will start by
stating the relationship at the highest level and then break this down to the
level of detail required to establish the answer. It saves both space and
complications if you only breakdown the formula into constituent parts when
required.
.EQ I
R sub U - VC sub TS =~~ FC sub S
.EN
The price is a component of the revenue so we will break the #R sub U# down
into its constituent parts. The costs we will leave alone.
.EQ I
P sub 2 ( 1 - c%) left [ k sub s + ( d - 1 )r right ] - VC sub TS 
=~~ FC sub S
.EN
We can now resolve for #P sub 2#:
.EQ I
P sub 2 ( 1 - c%) left [ k sub s + ( d - 1 )r right ]
lm FC sub S + VC sub TS 
.EN
.sp -0.6v
.EQ I
P sub 2
lineup =~~
{ FC sub S + VC sub TS }
over 
{ ( 1 - c%) left [ k sub s + ( d - 1 )r right ] }
.EN
We can now add in the numbers to establish the answer:
.EQ I
P sub 2 lm
{ FC sub S + VC sub TS }
over 
{ ( 1 - c%) left [ k sub s + ( d - 1 )r right ] }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ 11.09 + 61.98 }
over 
{ ( 1 - 0.03) 42 }
.EN
.sp -0.6v
.EQ I
lineup =~~
73.07
over 
40.74
.EN
.sp -0.6v
.EQ I
lineup =~~
1.79 ~\[Po]/kg
.EN
This is the price before the deduction of the sales commission. The price
required after commission would be:
.EQ I
P sub 3 lm P sub 2 times ( 1 - c% )
.EN
.sp -0.6v
.EQ I
lineup =~~
1.79 ( 1 - 0.03 )
.EN
.sp -0.6v
.EQ I
lineup =~~
1.736 \(dg ~\[Po]/kg
.EN
.FS
\(dg We have focused on live weights. If you are interested in the dead weight
price you can divide the price by the meat yield. If the meat yield is 45% the
price required would be # 1.736 over 0.45 = 3.86 ~\[Po]/kg #
.FE
.
.XXXX 0 5 "Breakeven - purchase price per kg"
.LP
It is also possible to resolve the breakeven equation for the purchase price #P
sub 1#. When resolved for #P sub 1 # we have established the maximum price that
can be paid per kilogram to purchase a store lamb. We will again start with the
breakeven equation:
.EQ I
R sub U - VC sub TS =~~ FC sub S
.EN
.RS
.EQ I
R sub U 
- { left [ PW sub B + MC + d  (OW sub B ) right ] } over { ( 1 - m% ) }
=~~
FC sub S 
.EN
.sp -0.6v
.EQ I
R sub U ( 1 - m% )
- left [ PW sub B + MC + d  (OW sub B ) right ]
=~~
FC sub S ( 1 - m%  )
.EN
.sp -0.6v
.EQ I
R sub U ( 1 - m% )
- left [ ( k sub s ) (  P sub 1 ) + v + t + MC + d  (OW sub B ) right ]
=~~
FC sub S ( 1 - m%  )
.EN
.sp -0.6v
.EQ I
R sub U ( 1 - m% )
- ( k sub s ) (  P sub 1 ) - v - t - MC - d  (OW sub B )
=~~
FC sub S ( 1 - m%  )
.EN
.sp -0.6v
.EQ I
- ( k sub s ) (  P sub 1 )
=~~
FC sub S ( 1 - m%  )
- R sub U ( 1 - m% )
+ v + t + MC + d  (OW sub B )
.EN
.sp -0.6v
.EQ I
( k sub s ) (  P sub 1 )
=~~
-FC sub S ( 1 - m%  )
+ R sub U ( 1 - m% )
- v - t - MC - d  (OW sub B )
.EN
.RE
.EQ I
P sub 1
=~~
{ ( 1 - m% ) left [ R sub U - FC sub S  right ]
- left [ v + t + MC + d  (OW sub B ) right ] }
over 
{ k sub s }
.EN
We can now plug in the numbers and establish the maximum price per kilogram to
be paid for a 30 kg lamb:
.EQ I
P sub 1
lm
{ ( 1 - m% ) left [ R sub U - FC sub S  right ]
- left [ v + t + MC + d  (OW sub B ) right ] }
over 
{ k sub s }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ ( 1 - 0.03 ) left [ 85.55 - 11.09  right ]
- left [ 3 + 2 + 0.45 + 9.667 right ] }
over 
30
.EN
.sp -0.6v
.EQ I
lineup =~~
{ 72.23 - 15.12 }
over 
30
.EN
.sp -0.6v
.EQ I
lineup =~~
1.904 ~\[Po]/kg
.EN
Which equates to \[Po]57.11 for a 30 kg lamb. I will leave you to do the check
this time. :)
.
.XXXX 0 5 "Breakeven - mortality rate"
.LP
The mortality rate has a large impact as it affects all the costs and the
revenues. We will start again with the breakeven equation:
.EQ I
R sub U - VC sub TS =~~ FC sub S
.EN
As the mortality rate affects all the costs and the revenue it is easier if we
work from the total revenue and total costs, # left [ R sub U - VC sub TS right
] Q sub S =~~ FC #. This simplifies the transposing of the equation by removing
the affect of the mortality rate on the fixed cost allowing us to state it as
an absolute value #FC# and not as a unit cost affected by the mortality #FC sub
S#.\(dg
.FS
\(dg It is possible to complete the calculation at a unit level but you have to
use the unit fixed cost based on the number of lambs bought as it not affected
by the mortality rate.
.EQ 
 m%  
=~~
{ R sub U - PW sub B - d (OW sub B ) - FC sub B  }
over
{  R sub U + cd }
=~~
{ 85.55 - 50.00 - 9.667 - 10.76  }
over
{  85.55 + 15 }
=~~
0.1504 ~or ~15.04%
.EN
.FE
.
.KS
.EQ I
left [ R sub U - VC sub TS right ] Q sub S =~~ FC
.EN
.RS
.EQ I
left [ R sub U - VC sub TS right ] Q sub B ( 1 - m% ) 
=~~
FC
.EN
.sp -0.6v
.EQ I
R sub U Q sub B ( 1 - m% ) 
- { left [ PW sub B + MC + d  (OW sub B ) right ] } over { ( 1 - m% ) }
Q sub B ( 1 - m% ) 
=~~
FC
.EN
.sp -0.6v
.EQ I
R sub U Q sub B ( 1 - m% ) 
- left [ PW sub B + MC + d  (OW sub B ) right ] Q sub B 
=~~
FC
.EN
.sp -0.6v
.EQ I
R sub U Q sub B ( 1 - m% ) 
- left [ PW sub B + m%(cd) + d  (OW sub B ) right ] Q sub B 
=~~
FC
.EN
.sp -0.6v
.EQ I
R sub U Q sub B ( 1 - m% ) 
- left [ Q sub B (PW sub B ) + Q sub B  m%(cd) + d (OW sub B )Q sub B
right ] 
=~~
FC
.EN
.sp -0.6v
.EQ I
R sub U Q sub B ( 1 - m% ) 
- Q sub B (PW sub B ) - Q sub B m%(cd)  - d (OW sub B )Q sub B
=~~
FC
.EN
.sp -0.6v
.EQ I
R sub U Q sub B ( 1 - m% ) 
- Q sub B m%(cd)
=~~
FC
+ Q sub B (PW sub B )
+ d (OW sub B )Q sub B
.EN
.sp -0.6v
.EQ I
R sub U Q sub B 
- R sub U Q sub B ( m% ) 
- Q sub B m%(cd)
=~~
FC
+ Q sub B (PW sub B )
+ d (OW sub B )Q sub B
.EN
.sp -0.6v
.EQ I
- R sub U Q sub B ( m% ) 
- Q sub B m%(cd)
=~~
FC
+ Q sub B (PW sub B )
+ d (OW sub B )Q sub B
- R sub U Q sub B 
.EN
.sp -0.6v
.EQ I
R sub U Q sub B ( m% ) 
+ Q sub B m%(cd)
=~~
-FC
- Q sub B (PW sub B )
- d (OW sub B )Q sub B 
+ R sub U Q sub B 
.EN
.sp -0.6v
.EQ I
Q sub B ( m% ) 
left [ R sub U + cd right ]
=~~
Q sub B left [ 
R sub U 
- PW sub B
- d (OW sub B )
right ]
-FC
.EN
.RE
.EQ I
m%  
=~~
{ Q sub B left [ R sub U - PW sub B - d (OW sub B ) right ] -FC }
over
{ Q sub B left [ R sub U + cd right ] }
.EN
.KE
At last we have isolated #m%# and can now enter the figures we have previously
established to resolve the breakeven mortality rate:
.EQ I
m%  lm
{ Q sub B left [ R sub U - PW sub B - d (OW sub B ) right ] -FC }
over
{ Q sub B left [ R sub U + cd right ] }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ 3,000 left [ 85.55 - 50.00 - 9.667 right ] - 32,272 }
over
{ 3,000 left [ 85.55 + 15 right ] }
.EN
.sp -0.6v
.EQ I
lineup =~~
45,377
over
301,650
.EN
.sp -0.6v
.EQ I
lineup =~~
0.1504 ~or ~15.04%
.EN
We can check the mortality rate by recalculating the costs and the revenues
with the breakeven mortality rate:
.EQ I
TR lm P sub 3 ( k sub f ) Q sub S
.EN
.sp -0.6v
.EQ I
lineup =~~
P sub 3 ( k sub f ) Q sub B ( 1 - m% )
.EN
.sp -0.6v
.EQ I
lineup =~~
2.037 ( 42 ) 3,000 ( 1 - 0.1504 )
.EN
.sp -0.6v
.EQ I
lineup =~~
85.55 ( 2,549 )
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]218,060
.EN
.KS
The mortality rate has reduced the number of lambs to be sold down from a
potential 3,000 to 2,549.
.EQ I
TC lm VC sub TS + FC
.EN
.sp -0.6v
.EQ I
lineup =~~
{  PW sub B + MC + d  (OW sub B ) } over {  1 - m%  } Q sub S
+ 
FC
.EN
.sp -0.6v
.EQ I
lineup =~~
{  PW sub B + m%(cd) + d  (OW sub B ) }
over {  1 - m%  }
Q sub B ( 1 - m% )
+ 
FC
.EN
.sp -0.6v
.EQ I
lineup =~~
{  50 + 0.1504(15) + 9.667 }
over {  1 - 0.1504 }
3,000 ( 1 - 0.1504 )
+ 
32,272
.EN
.sp -0.6v
.EQ I
lineup =~~
72.88 (2,549)
+ 
32,272
.EN
.sp -0.6v
.EQ I
lineup =~~
\[Po]218,041
.EN
.KE
The mortality rate has raised the variable costs per lamb to #\[Po]72.88# from
#\[Po]61.98#. We could have simplified the equation during the check but we
would not have seen the rise in the costs due to the mortality.
.
.XXXX 0 4 "Breakeven with a margin"
.LP
As useful as they have been none of the previous breakeven examples have
included a margin. In this section we will examine how to apply the margin and
recalculate the breakeven.
.
.XXXX 0 5 "Breakeven with a margin (percentage) - sale price per kg"
.LP
We can apply the margin as a percentage to the cost structure. We will again
start with the standard breakeven equation:
.EQ I
R sub U - VC sub TS =~~ FC sub S
.EN
We can now apply the margin to the equation by multiplying the costs by the
margin #M%#.
.EQ I
R sub U - M% ( VC sub TS )  =~~ M% ( FC sub S )
.EN
We can now expand the revenue #R sub U# to reveal the sale price #P sub 2# and
resolve:
.EQ I
P sub 2 ( 1 - c%) left [ k sub s + ( d - 1 )r right ] - M% ( VC sub TS )  =~~ M% ( FC sub S )
.EN
.RS
.EQ I
P sub 2 ( 1 - c%) left [ k sub s + ( d - 1 )r right ]
=~~ M% ( FC sub S ) + M% ( VC sub TS )  
.EN
.sp -0.6v
.EQ I
P sub 2 ( 1 - c%) left [ k sub s + ( d - 1 )r right ]
=~~ M% ( FC sub S + VC sub TS )  
.EN
.RE
.EQ I
P sub 2
=~~ 
{ M% ( FC sub S + VC sub TS ) }
over 
{ ( 1 - c%) left [ k sub s + ( d - 1 )r right ] }
.EN
If we want to make a 15% margin we can first establish a multiplier\(dg by
setting the cost equal to 1:
.FS
\(dg The sale price is equal to # cost over { ( 1 - margin % ) }#. Therefore if
you have a product that cost \[Po]5.32 and you wanted to add a 25% margin you
can either divide by # ( 1 - margin% )# giving #5.32 over { 1 - 0.25 } =
\[Po]7.09 # or you can do the division independently to create a factor which
can be used as a multiplier #5.32 times 1 over { 1 - 0.25 } = 5.32 times 1.33 =
\[Po]7.09 #. The advantage of the factor is that you do not have to complete
the margin calculation every time you want to know the sale price of a product,
provided you have a fixed margin, and more importantly, in this case, we do not
add another fraction to the equation.
.FE
.EQ I
M% =~~
Cost over { ( 1 - margin% ) }
=~~
1 over { ( 1 - 0.15 ) }
=~~
1.176
.EN
.KS
We will now fill in the formula with the numbers from our previous work:
.EQ I
P sub 2
lm
{ M% ( FC sub S +  VC sub TS ) }
over
{ ( 1 - c%) left [ k sub s + ( d - 1 )r right ] }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ 1.176 ( 11.09 +  61.98 ) }
over
{ ( 1 - 0.03) left [ 42 ] }
.EN
.sp -0.6v
.EQ I
lineup =~~
85.93
over
40.74
.EN
.sp -0.6v
.EQ I
lineup =~~
2.11 ~\[Po]/kg
.EN
.KE
.
.XXXX 0 5 "Breakeven with a margin (value) - sale price per kg"
.LP
We will now look at the equation for a margin as expressed by an absolute value
such as \[Po]10. We will again start with the standard breakeven equation:
.EQ I
R sub U - VC sub TS =~~ FC sub S
.EN
As the margin is an absolute value and there is no multiplication we can simply
apply the margin to the right hand side of the equation and resolve for the
sale price #P sub 2#.
.EQ I
R sub U - VC sub TS =~~ FC sub S + M
.EN
.RS
.EQ I
R sub U =~~ FC sub S + VC sub TS + M
.EN
.sp -0.6v
.EQ I
P sub 2 ( 1 - c%) left [ k sub s + ( d - 1 )r right ]
=~~ FC sub S +  VC sub TS + M
.EN
.RE
.EQ I
P sub 2
=~~
{ FC sub S +  VC sub TS + M }
over
{ ( 1 - c%) left [ k sub s + ( d - 1 )r right ] }
.EN
We can now fill in the formula with the numbers from our previous work to
establish the sale price required for a \[Po]10 profit per lamb:
.EQ I
P sub 2
=~~
{ FC sub S +  VC sub TS + M }
over
{ ( 1 - c%) left [ k sub s + ( d - 1 )r right ] }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ 11.09 +  61.98 + 10  }
over
{ ( 1 - 0.03) left [ 42 ] }
.EN
.sp -0.6v
.EQ I
lineup =~~
83.07
over
40.74
.EN
.sp -0.6v
.EQ I
lineup =~~
2.04 ~\[Po]/kg
.EN
.
.XXXX 0 5 "Breakeven with a margin (percentage) - purchase price per kg"
.LP
It is often useful to resolve for the purchase price #P sub 1# including your
margin. We will again start with the breakeven equation:
.EQ I
R sub U - VC sub TS =~~ FC sub S
.EN
We can now apply the margin to the equation by multiplying the costs by the
margin #M%#.
.EQ I
R sub U - ( VC sub TS )M% =~~ ( FC sub S )M%
.EN
.KS
The purchase price #P sub 1# forms part of the #VC sub TS# so will expand this
component and resolve:
.EQ I
R sub U 
- { left [ PW sub B + MC + d  (OW sub B ) right ] M% } over { ( 1 - m% ) }
=~~
( FC sub S ) M%
.EN
.RS
.EQ I
R sub U ( 1 - m% )
- left [ PW sub B + MC + d  (OW sub B ) right ] M%
=~~
FC sub B M%
.EN
.sp -0.6v
.EQ I
R sub U ( 1 - m% )
- left [ ( k sub s ) (  P sub 1 ) + v + t + MC + d  (OW sub B ) right ] M%
=~~
FC sub B M%
.EN
.sp -0.6v
.EQ I
R sub U ( 1 - m% )
- left [ M%( k sub s ) (  P sub 1 ) + M%(v) + M%(t) + M%(MC)
+ d  (OW sub B )M% right ]
=~~
FC sub B M%
.EN
.sp -0.6v
.EQ I
R sub U ( 1 - m% )
- M%( k sub s ) (  P sub 1 ) - M%(v) - M%(t) - M%(MC) - d  (OW sub B )M%
=~~
FC sub B M%
.EN
.sp -0.6v
.EQ I
- M%( k sub s ) (  P sub 1 )
=~~
FC sub B M%
- R sub U ( 1 - m% )
+ M%(v) + M%(t) + M%(MC) + d  (OW sub B )M%
.EN
.sp -0.6v
.EQ I
M%( k sub s ) (  P sub 1 )
=~~
-FC sub B M%
+ R sub U ( 1 - m% )
- M%(v) - M%(t) - M%(MC) - d  (OW sub B )M%
.EN
.RE
.EQ I
P sub 1
=~~
{ ( 1 - m% ) R sub U
- M% left [ FC sub B  + v + t + MC + d  (OW sub B ) right ] }
over 
{ M% ( k sub s )  }
.EN
.KE
We can now plug in the numbers and establish the maximum price to be paid, for
a 30 kg lamb in this instance to achieve a margin of 15%:
.EQ I
P sub 1
=~~
{ ( 1 - m% ) R sub U
- M% left [ FC sub B  + v + t + MC + d  (OW sub B ) right ] }
over 
{ M% ( k sub s )  }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ ( 1 - 0.03 ) 85.55
- 1.176 left [ 10.76  + 3 + 2 + 0.45 + 9.667 right ] }
over 
{ 1.176 ( 30 )  }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ 82.98 - 30.43 }
over 
35.28
.EN
.sp -0.6v
.EQ I
lineup =~~
1.49 ~\[Po]/kg
.EN
As long as you stay within the limitations of the model, which is fattening
lambs over a max period of 120 days on stubble turnips and hay, you can use the
model to establish how much to pay for lambs based on the costs moving in a
linear fashion.
.LP
For example, how much should you pay for 30 kg lambs which will only have a
growth rate of 0.12 kg per day and a mortality rate of 5%, if they are to to be
sold at a finished weight of 42 kg? It is assumed that the sale price per
kilogram remains the same.
.LP
First the growth rate of 0.12 kg per day can be converted into days on farm:
.EQ I
"Target days on farm" ~~d lm
{ "Finished weight" - "store weight" } over "rate of gain per day" + 1
=~~
left [ { k sub f - k sub s } over r right ] + 1
.EN
.sp -0.6v
.EQ I
lineup =~~
left [ { 42 - 30 }
over 0.12  right ] + 1
=~~
101 ~ days
.EN
We can use the equation we have previously derived but this time we will have
to expand the #MC# into its constituent parts to include the mortality.
.EQ I
P sub 1
lm
{ ( 1 - m% ) R sub U
- M% left [ FC sub B  + v + t + m%cd + d  (OW sub B ) right ] }
over 
{ M% ( k sub s )  }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ ( 1 - 0.05 ) 85.55
- 1.176 left [ 10.76  + 3 + 2 + 0.05(15) + 101 (0.11935 ) right ] }
over 
{ 1.176  ( 30 )  }
.EN
.sp -0.6v
.EQ I
lineup =~~
{ 81.27 - 33.59 }
over 
35.28
.EN
.sp -0.6v
.EQ I
lineup =~~
1.35 ~\[Po]/kg
.EN
.
.XXXX 0 5 "Breakeven with a margin (value) - purchase price per kg"
.LP
It is also possible to resolve for the purchase price with the margin
represented as an value. We will use \[Po]10 again.
.LP
The standard breakeven equation we have been using is:
.EQ I
R sub U - VC sub TS =~~ FC sub S
.EN
As the margin is an absolute value and there is no multiplication we can simply
apply the margin to the right hand side of the equation expand the #VC sub TS#
and resolve for #P sub 1#.
.EQ I
R sub U - VC sub TS =~~ FC sub S + M
.EN
.RS
.EQ I
R sub U - { left [ PW sub B + MC + d  (OW sub B ) right ] } over { ( 1 - m% ) } 
=~~ FC sub S + M
.EN
.sp -0.6v
.EQ I
R sub U ( 1 - m% )
- left [ PW sub B + MC + d  (OW sub B ) right ]
=~~
( M + FC sub S ) ( 1 - m% ) 
.EN
.sp -0.6v
.EQ I
R sub U ( 1 - m% )
- left [ ( k sub s ) (  P sub 1 ) + v + t + MC + d  (OW sub B ) right ]
=~~
( M + FC sub S ) ( 1 - m% ) 
.EN
.sp -0.6v
.EQ I
R sub U ( 1 - m% )
- ( k sub s ) (  P sub 1 ) - v - t - MC - d  (OW sub B )
=~~
( M + FC sub S ) ( 1 - m% ) 
.EN
.sp -0.6v
.EQ I
- ( k sub s ) (  P sub 1 )
=~~
( M + FC sub S ) ( 1 - m% ) 
- R sub U ( 1 - m% )
+ v + t + MC + d  (OW sub B )
.EN
.sp -0.6v
.EQ I
( k sub s ) (  P sub 1 )
=~~
-( M + FC sub S ) ( 1 - m% ) 
+ R sub U ( 1 - m% )
- v - t - MC - d  (OW sub B )
.EN
.RE
.EQ I
 P sub 1
=~~
{
( 1 - m% )
left [ R sub U -( M + FC sub S ) right ] 
- left [ v + t + MC + d  (OW sub B ) right ] 
} over k sub s
.EN
We can now fill in the formula with the numbers from our previous work to
establish the maximum price to pay for a 30 kg lamb and achieve a margin of
\[Po]10 per lamb.
.EQ I
 P sub 1
lm
{ ( 1 - m% )
left [ R sub U -( M + FC sub S ) right ] 
- left [ v + t + MC + d  (OW sub B ) right ] 
} over k sub s
.EN
.sp -0.6v
.EQ I
lineup =~~
{ ( 1 - 0.03 )
left [ 85.55 - ( 10 + 11.09 ) right ] 
- left [ 3 + 2 + 0.45 + 81  (0.11935) right ] 
} over 30
.EN
.sp -0.6v
.EQ I
lineup =~~
47.41
over 30
.EN
.sp -0.6v
.EQ I
lineup =~~
1.58 ~\[Po]/kg
.EN
.
.XXXX 0 3 "Growth rates"
.LP
The table below is from the EBLEX publication "Growing and finishing lambs for
better returns". The lamb weights are interpreted as normally distributed with
the range of 30 - 35 kilograms representing the center of the bell curve.
.TS
tab (#) center;
l c c c .
#_#_#_
#Long keep#Medium keep#Short keep
_
Time to finish (weeks) #>12#6 - 12#<6
Time to finish (days) #>84#42 - 84#<42
Store weight (kg) #< 30#30 - 35#>35
Total gain (kg)#12 - 18#6 - 12#5 - 6
Gain per day (kg)#0.08 - 0.1#0.09 - 0.12#0.14 - 0.16
_
.TE
It can be seen that larger lambs appear to have better growth rates. This is
probably the impact of better genetics, a good birth weight and access to milk,
giving a better start in life. It is best practice to divide up the lambs into
mobs according to their purchase weight and target time to reach the finishing
weight.
.LP
In general, growth rates are dependent on the quality and quantity of the feed.
Higher amounts of energy, as measured in megajoules (MJ) of metabolisable
energy (ME) per kilogram of dry matter or MJ ME/kg DM as it often expressed,
lead to higher growth rates. If a lamb is born and has access to unlimited
amounts of milk, which is dependent on the quality and quantity of grass
available to the ewe, it is possible to achieve growth rates as high as 0.4
kg/day.
.LP
Below is a table of the feed values typically associated with turnips and hay:
.TS
tab (#) center;
l c c.
#_#_
#Stubble Turnips#Hay
_
Fresh yield (kg/ha)# 40,000 - 60,000
DM (%) # 12 - 15#85
Energy (MJ ME/kg DM)#10 - 11#8 - 10
Protein (g/kg DM )#17 - 18#15 - 20
Max lamb growth (kg/day)# 0.27#
Days to graze from planting# 60-100#
_
.TE
The graph below showing the relationship between the energy of the feed and the
growth rate is taken from "400 Plus, A guide to improved lamb growth for
farmers and advisers" produced by the New Zealand Sheep Council. The graph is
found in sheep publications across the world to emphasis the requirement for
good quality feed and I have used a New Zealand publication as it was to hand
but it can also be found in UK publications.
.br
.sp
.ce 1
Live weight gain of a 30 kg lamb and the energy value of the diet
.sp -3
.G1
frame invis ht 1.5 wid 4.5 left solid bot solid
label left "Live weight gain (g/day)" left .3
label bot "Energy value of diet (MJ ME/kg DM)"
draw solid
ticks bot out from 7 to 13 by 1
7 -200
8 -100
9 0
10 100
11 200
12 300
13 400
.G2
The equation for the graph above is #y = x(100) - 900# which would imply that
11 MJ ME/kg of DM would deliver a growth rate of 200g per day. The stubble
turnips in the table have a maximum growth rate of 270 grams per day which
would imply 11.7 MJ ME/kg of DM. It is also worth noting that at 9 MJ ME/kg of
DM the equation would imply a growth rate of zero, # 9(100) - 900 = 0# and
below 9 MJ ME/kg of DM a loss of weight.
.
.XXXX 0 2 "Degree of Operating Leverage"
.LP
In finance leverage is a technique that companies use to increase their assets,
cash flows and returns. There are two main types of leverage:
.IP "Financial" 10
Financial leverage can be increased with asset backed finance, issuing bonds or
occurring debt directly with a bank, thereby increases the amount of debt
relative to equity in the business.
.IP "Operating" 10
Operating leverage can can be attained by increasing the fixed costs as a
percentage of total costs, which magnifies the upside or downside of the
operating profit.
.LP
It is important to understand that leverage increases the risk to the business
by creating unavoidable charges which can lead to the demise of the enterprise
in difficult times. The degree of operating leverage (DOL) is used to quickly
estimate what impact various percentage changes in sales will have on profits,
without the necessity of preparing detailed income statements. If a company is
near its break-even point, then even a small percentage increase in sales can
yield large percentage increases in profits. This explains why companies will
often work very hard for only a small increase in sales volume. 
.sp 
.XXXX 0 2 "Cost Structure"
.LP
Because fixed costs are incurred regardless of the level of sales, companies
with higher fixed costs find it difficult to reduce these costs in the
short-run. As a result, companies with higher proportions of fixed costs have
higher operating leverage and are considered to have more risky operations.
Companies with a cost structure consisting of significant amounts of labour
with fewer capital assets have lower fixed costs and higher variable costs.
Variable costs are easier to reduce on a short-term basis, which in turn,
implies lower operating leverage and less risky operations. 
.IP "Lower operating leverage" 15
This implies lower fixed costs and higher variable costs. A company with low
operating leverage has to achieve lower sales to cover its fixed costs than a
company with higher operating leverage. Once the company crosses the break-even
point where all its fixed costs are covered, it can earn incremental profit in
terms of selling price minus the variable cost which will not be substantial as
the variable cost itself are high. When the operating leverage is low the fixed
costs are low, therefore, the break-even units which a company needs to sell in
will be comparatively lower than a company with higher operating leverage.
.IP "Higher operating leverage" 15
This implies lower variable costs and higher fixed costs. A company with higher
operating leverage has higher fixed costs and must, therefore, achieve greater
sales to break-even. On the other hand once the break-even is achieved the
company will earn a higher profit on each item sold as the variable costs are
lower than a company with low operating leverage. 
.LP
Companies generally prefer to have a lower operating leverage so even if there
is a decrease in sales it should not be difficult to cover the fixed costs.
Conversely companies with higher operating leverage have profits which are more
sensitive to changes in sales volume.
.LP
Constant monitoring of operating leverage is more important for a firm having
high operating leverage, since a small percentage change in sales can result in
a dramatic increase (or decrease) in profits. A firm must be especially careful
to forecast its sales in these situations, since a small forecasting error
translates into much larger errors in both net income and cash flows.
.LP
The level of operating leverage can have a profound impact on
pricing policy, since a company with a large amount of operating leverage must
be careful not to set its prices so low that it can never generate enough
contribution margin to fully offset its fixed costs
.sp 
.XXXX 0 2 "Measuring Operating Leverage"
.LP
Assume two companies have maintained the same amount of revenue and the same
amount of operating profit for the past two years, and that both companies
experience a 15 percent increase in revenue during the current year. The change
in operating income for each of the two companies will differ depending on each
company's degree of operating leverage.
.LP
There are two components of operating leverage, contribution margin and
operating income. The higher the contribution margin the more quickly profits
increase with sales. This result occurs because higher contribution margins
amounts have lower variable costs in proportion to total costs. Operating
income typically consists of income before interest and income taxes or EBIT.
.sp
Degree of operating leverage can be calculated in a number of ways:
.EQ I
"Degree of operating leverage"
=
"change in operating income" over "changes in sales"
.EN
.EQ I
"Degree of operating leverage"
=
"contribution margin" over "operating income"
.EN
.EQ I
"Degree of operating leverage"
=
"contribution margin %" over "operating margin %"
.EN
For the purposes of illustration  an income statement with which to calculate
the DOL has been constructed below:
.TS
tab (#) center;
cp-2 s
a n .
.sp 5p
REVENUE ASSUMPTIONS#
_
Revenues (Per diem)#500
Number of days worked#250
.TE
.
.TS
tab (#) center;
cp-3 s .
INCOME STATEMENT#
_
.sp 5p
.T&
lb n
l n
lb n
l n
lb n
l n .
Revenue#125,000
Variable Costs#50,000
_
Contribution Margin#75,000
Total Operating Costs#44,000
_
EBIT#31,000
Capital Charge#9,120
_
Added Value pre Tax#21,880
.TE
The income statement uses the "Total Operating Costs" as calculated in the
break-even analysis for the fixed cost component in Section 20.3. It is
important to make sure you compare apples with apples and this is an income
statement so it includes non cash charges. The "Capital Charge" has been
deducted based on the previous calculation in Section 20.3.1 and it is inserted
to show the value that has been created for the shareholder. 
.EQ I
"Degree of operating leverage"
=
"contribution margin" over "EBIT" = 75,000 over 31,000 = 2.42
.EN
.sp 
.XXXX 0 2 "Interpreting the DOL"
.LP
The DOL indicates the number of times that the contribution margin exceeds the
company's operating income. A company with higher DOL has more extreme
fluctuations in operating income than a company with a lower DOL when a change
in sales revenue occurs. A high DOL implies a more risky operating structure
because of the volatility of the change in profit, conversely a lower DOL
amount implies a less risky operating structure. 
.sp 
.XXXX 0 2 "Using the DOL"
.LP
The DOL can be used to predict the effect that a specified increase in sales
will have on the operating income. One approach to determine the effect is to
prepare a revised income statement that reflects the increase in sales, which
is both time consuming and unnecessary. Using the operating leverage approach,
you can quickly estimate the percentage change in operating income by
multiplying the DOL by the anticipated percentage change in sales. Using the
income statement a 10% increase in sales would have the following result.
.EQ I
"Percentage increase in operating income" = 2.42 times 10% = 24.20%
.EN
The 24.2% change represents the "increase" in operating income due to a 10%
increase in sales. To determine the GBP change in profit, multiple the
percentage change in EBIT times the original profit of 31,000
.EQ I
"GBP change in operating income" = 24.2% times 31,000 = 7,502
.EN
Operating income is expected to increase by 7,502 if sales increase by 10%. To
determine the estimated new profit level as a result of the change, either add
the original profit to the increase or multiply the original value by 1.242
.EQ I
"Estimated new EBIT"= 7,502 + 31,000 = 38,502
.EN
.EQ I
"Estimated new EBIT" = (1 + 24.2%) times 31,000 = 1.242 times 31,000 = 38,502
.EN
Below is a table showing a range of possible EBIT values for a range of
increases in sales.
.TS
tab (#) center;
c c c c c c c
n n n n n n n .
% \[ua] Revenue#Revenue#EBIT#\[*D] EBIT#% \[*D] EBIT#Extra Days#Total Days
_
10#137,500#38,500#7,500#24.2#25#275
20#150,000#46,000#15,500#48.4#50#300
30#162,500#53,500#22,500#72.6#75#325
_
.TE
Note that a similar effect occurs if revenue is expected to decline. Leverage
works in both directions. The new EBIT value can be calculated as follows:
.EQ I
"Estimated new EBIT" = ( 1 - 24.2%)  times 31,000 = 0.758 times 31,000 = 23,500
.EN
.
.TS
tab (#) center;
c c c c c c c
n n n n n n n .
% \[da] Revenue#Revenue#EBIT#\[*D] EBIT#% \[*D] EBIT#Extra Days#Total Days
_
(10)#112,500#23,500#(7,500)#(24.2)#(25)#225
(20)#100,000#46,000#(15,500)#(48.4)#(50)#200
(30)#87,500#53,500#(22,500)#(72.6)#(75)#175
_
.TE
The DOL can be used to quickly estimate what impact various percentage changes
in sales will have on profits, without the necessity of preparing detailed
income statements. As shown by our example the effect of operating leverage can
be dramatic. If a company is near its break even point then even a small
percentage increases in sales can yield large percentage increases in profits.
This explains why management will often work very hard for only a small
increase in sales volume. If the DOL is 5, then a 6% increase in sales would
translate into a 30% increase in profits.
.LP
You also can use the degree of operating leverage formula to assess the
relationship between costs and profit. If you minimize your fixed costs, you
can increase your profit without changing your sale price, contribution margin,
or units sold. If you eliminated the fixed costs the entire contribution margin
would go towards the profit!
